### ISSUE TITLE
Host ks cannot enter the member ks.

### ISSUE THREAD

**Issue by gzlj** [kubesphere/community#108]
Host ks cannot enter the member ks.
导入了一个集群，但是鼠标指向集群，点击详细的时候，弹出"会话超时或此账户在其它地方登录，请重新登录"。

**Comment by rayzhou2017** [comment]
Did you follow the guide to enable the clusterRole of the member cluster to `member`? https://github.com/kubesphere/community/tree/master/sig-multicluster/how-to-setup-multicluster-on-kubesphere

**Comment by rayzhou2017** [comment]
On the member cluster, change the role.
kubectl edit cc ks-installer -n kubesphere-system

**Comment by gzlj** [comment]
thank you. Now I have a host cluster and a member cluster.
