### ISSUE TITLE
Register a CNCF Webinar

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#190]
@duanjiong @zheng1 Please refer to this format and provide the corresponding topic and outline for Porter, as well as its scenario with KubeSphere. See [this example](https://www.cncf.io/webinars/k8s-audit-logging-deep-dive/) for details. Please also give an available register date for the CNCF webinar, how about 4th, November?

![image](https://user-images.githubusercontent.com/40452856/96735074-bfbddc80-13ed-11eb-9b49-1d84ff7ab333.png)

**Comment by FeynmanZhou** [comment]
@duanjiong Please write an outline for the CNCF Webinar ASAP, Chinese or English are fine.

**Comment by duanjiong** [comment]
PorterLB:  expose you service in Bare Metal environment

As we know, In the cloud-hosted Kubernetes cluster, the cloud providers (AWS, GCP, Azure, etc.) usually provide the Load Balancer to assign IPs and expose the service to outside.

However, the service is hard to expose in a bare metal cluster since Kubernetes does not provide a load-balancer solution for bare metal environment. Fortunately, PorterLB allows you to create Kubernetes services of type "LoadBalancer" in bare metal clusters, which makes you have consistent experience with the cloud.

In this session you will learn about

- The PorterLB architecture
- How to handle conflicts with Calico's BGP port
- How to deploy PorterLB in KubeSphere
- How to expose your service in BGP mode
- How to expose your service in Layer2 mode

This webinar will be delivered in Chinese.

**Comment by FeynmanZhou** [comment]
## Title 

Exposing your Services from Hybrid Cloud using PorterLB and KubeSphere

## Abstract

As we know, In the cloud-hosted Kubernetes cluster, the cloud providers (AWS, GCP, Azure, etc.) usually provide the Load Balancer to assign IPs and expose the service to outside. There is not a graceful solution to expose services of type "LoadBalancer" in bare metal clusters which makes them second class citizens in the Kubernetes ecosystem.

Fortunately, PorterLB allows you to expose services in bare metal clusters which makes you have a consistent experience with the cloud. You can easily leverage PorterLB and KubeSphere to manage and expose your services crossing multi-cloud and multi-cluster environments.

## Outline

In this session, you will learn about

- Introduction to KubeSphere: an open source Kubernetes platform for hybrid cloud 
- Introduction to PorterLB and its cloud native architecture
- How to deploy PorterLB on KubeSphere
- How to expose your services crossing public cloud and data center

This webinar will be delivered in Chinese.

**Comment by FeynmanZhou** [comment]
> ## Title
> Exposing your Services from Hybrid Cloud using PorterLB and KubeSphere
> 
> ## Abstract
> As we know, In the cloud-hosted Kubernetes cluster, the cloud providers (AWS, GCP, Azure, etc.) usually provide the Load Balancer to assign IPs and expose the service to outside. There is not a graceful solution to expose services of type "LoadBalancer" in bare metal clusters which makes them second class citizens in the Kubernetes ecosystem.
> 
> Fortunately, PorterLB allows you to expose services in bare metal clusters which makes you have a consistent experience with the cloud. You can easily leverage PorterLB and KubeSphere to manage and expose your services crossing multi-cloud and multi-cluster environments.
> 
> ## Outline
> In this session, you will learn about
> 
> * Introduction to KubeSphere: an open source Kubernetes platform for hybrid cloud
> * Introduction to PorterLB and its cloud native architecture
> * How to deploy PorterLB on KubeSphere
> * How to expose your services crossing public cloud and data center
> 
> This webinar will be delivered in Chinese.

@duanjiong @Sherlock113 @zheng1 I updated from my perspective, how about it?

**Comment by duanjiong** [comment]
> > ## Title
> > Exposing your Services from Hybrid Cloud using PorterLB and KubeSphere
> > ## Abstract
> > As we know, In the cloud-hosted Kubernetes cluster, the cloud providers (AWS, GCP, Azure, etc.) usually provide the Load Balancer to assign IPs and expose the service to outside. There is not a graceful solution to expose services of type "LoadBalancer" in bare metal clusters which makes them second class citizens in the Kubernetes ecosystem.
> > Fortunately, PorterLB allows you to expose services in bare metal clusters which makes you have a consistent experience with the cloud. You can easily leverage PorterLB and KubeSphere to manage and expose your services crossing multi-cloud and multi-cluster environments.
> > ## Outline
> > In this session, you will learn about
> > 
> > * Introduction to KubeSphere: an open source Kubernetes platform for hybrid cloud
> > * Introduction to PorterLB and its cloud native architecture
> > * How to deploy PorterLB on KubeSphere
> > * How to expose your services crossing public cloud and data center

In the public cloud, you should be using the cloud provider's lb plugin, not the porter.
Let's just focus on the bare metal clusters.

That's all.

> > 
> > This webinar will be delivered in Chinese.
> 
> @duanjiong @Sherlock113 @zheng1 I updated from my perspective, how about it?

**Comment by FeynmanZhou** [comment]
> > > ## Title
> > > Exposing your Services from Hybrid Cloud using PorterLB and KubeSphere
> > > ## Abstract
> > > As we know, In the cloud-hosted Kubernetes cluster, the cloud providers (AWS, GCP, Azure, etc.) usually provide the Load Balancer to assign IPs and expose the service to outside. There is not a graceful solution to expose services of type "LoadBalancer" in bare metal clusters which makes them second class citizens in the Kubernetes ecosystem.
> > > Fortunately, PorterLB allows you to expose services in bare metal clusters which makes you have a consistent experience with the cloud. You can easily leverage PorterLB and KubeSphere to manage and expose your services crossing multi-cloud and multi-cluster environments.
> > > ## Outline
> > > In this session, you will learn about
> > > 
> > > * Introduction to KubeSphere: an open source Kubernetes platform for hybrid cloud
> > > * Introduction to PorterLB and its cloud native architecture
> > > * How to deploy PorterLB on KubeSphere
> > > * How to expose your services crossing public cloud and data center
> 
> In the public cloud, you should be using the cloud provider's lb plugin, not the porter.
> Let's just focus on the bare metal clusters.
> 
> That's all.
> 
> > > This webinar will be delivered in Chinese.
> > 
> > 
> > @duanjiong @Sherlock113 @zheng1 I updated from my perspective, how about it?

Updated.

**Comment by zheng1** [comment]
> ## Title
> Exposing your Services from Hybrid Cloud using PorterLB and KubeSphere
> 
> ## Abstract
> As we know, the cloud providers (AWS, GCP, Azure, etc.) usually provide the Load Balancer to assign IPs and expose the service to outside in the cloud-hosted Kubernetes clusters. However, Kubernetes does not provide a load-balancer for bare metal clusters which makes them second class citizens in the ecosystem.
> 
> Fortunately, PorterLB allows you to expose services in bare metal clusters which makes you have a consistent experience with the cloud. You can easily leverage PorterLB and KubeSphere to manage and expose your services crossing multi-cloud and multi-cluster environments.
> 
> ## Outline
> In this session, you will learn about
> 
> * Introduction to KubeSphere: an open-source Kubernetes platform for hybrid cloud
> * Introduction to PorterLB and its cloud native architecture
> * How to deploy PorterLB on KubeSphere
> * How to expose your services from the data center (bare metal)
> 
> This webinar will be delivered in Chinese.

I see the title hasn't been changed. @FeynmanZhou

**Comment by Sherlock113** [comment]
Here is my version:

## Title

Exposing Your Services in Bare Metal Environment Using Porter and KubeSphere

## Abstract

As we know, cloud providers (AWS, GCP, Azure, etc.) usually provide the Load Balancer to assign IPs and expose services outside Kubernetes clusters hosted on their platform. However, Kubernetes does not provide a load balancer for bare metal clusters, which makes them second-class citizens in the ecosystem.

Fortunately, PorterLB allows you to expose services in bare metal clusters, providing you with a consistent experience that you can get from the cloud. You can easily leverage PorterLB and KubeSphere to manage and expose your services across multi-cloud and multi-cluster environments.

## Outline

In this session, you will learn:

- Introduction to KubeSphere: an open-source Kubernetes platform for hybrid cloud
- Introduction to PorterLB and its cloud-native architecture
- How to deploy PorterLB on KubeSphere
- How to expose your services from the data center (bare metal)

This webinar will be delivered in Chinese.

**Comment by FeynmanZhou** [comment]
> Here is my version:
> 
> ## Title
> Exposing Your Services in Bare Metal Environment Using Porter and KubeSphere
> 
> ## Abstract
> As we know, cloud providers (AWS, GCP, Azure, etc.) usually provide the Load Balancer to assign IPs and expose services outside Kubernetes clusters hosted on their platform. However, Kubernetes does not provide a load balancer for bare metal clusters, which makes them second-class citizens in the ecosystem.
> 
> Fortunately, PorterLB allows you to expose services in bare metal clusters, providing you with a consistent experience that you can get from the cloud. You can easily leverage PorterLB and KubeSphere to manage and expose your services across multi-cloud and multi-cluster environments.
> 
> ## Outline
> In this session, you will learn:
> 
> * Introduction to KubeSphere: an open-source Kubernetes platform for hybrid cloud
> * Introduction to PorterLB and its cloud-native architecture
> * How to deploy PorterLB on KubeSphere
> * How to expose your services from the data center (bare metal)
> 
> This webinar will be delivered in Chinese.

@Sherlock113 Thanks, we will adopt this one and submit it to webinar@cncf.io.
