### ISSUE TITLE
KubeSphere DevOps Community Meeting Notes / Agenda

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/community#223]
## Meeting Time

Beijing Time: Thursday at 16:30-17:30 Nov. 5, 2020

## Links

- DevOps User Guide: https://kubesphere.io/docs/devops-user-guide/
- Sig-DevOps: https://github.com/kubesphere/community/tree/master/sig-devops
- Slack: [Click to join](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE) and go to #sig-devops
- Chinese Forum: https://kubesphere.com.cn/forum/

## Organizers

- @zryfish 
- @shaowenchen 
- @LinuxSuRen 

### Nov. 5, 2020 (Beijing Time)

Agenda:

1. How to build a development environment: [Dev](https://kubesphere.com.cn/forum/d/2393-kubesphere-devops-30) and [Ops](https://kubesphere.com.cn/forum/d/2408-kubesphere-devops-30)
2. [Development List of DevOps 3.1.0](https://github.com/kubesphere/kubesphere/issues/3052)

**Comment by LinuxSuRen** [comment]
Considering create a team in the GitHub organization that contains all the members of sig-devops. It will be convenient that addressing this team.

Besides create an event on the Kubesphere Google calendar is also a good way to notify all the participant.

**Comment by shaowenchen** [comment]
Move to https://docs.google.com/document/d/1ZORl7ZhRlZxKXFle2LGPRJqXzlr6EDhu2A7qzjybfro/
