### ISSUE TITLE
Apply for Google Summer of Code in Feb

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#280]
Google Summer of Code will be started from 30, Jan. We need to apply for it and investigate the prerequisites we need to prepare.

Ref: https://summerofcode.withgoogle.com/get-started/

**Comment by FeynmanZhou** [comment]
@LinuxSuRen Did you start to investigate the GSoC 2021? We are getting closer to the registration date.

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen Did you start to investigate the GSoC 2021? We are getting closer to the registration date.

I did some. But I guess it's time to collect some project proposals now before it's too late.

**Comment by LinuxSuRen** [comment]
Google Summer of Code 2021 Timeline
Date | Event
-- | --
2020 |  
October 26 | Program announced
2021 |  
January 29 19:00 UTC | Mentoring organizations can begin submitting applications to Google
February 19 19:00 UTC | Mentoring organization application deadline
February 19 - March 8 | Google program administrators review organization applications
March 9 19:00 UTC | List of accepted mentoring organizations published
March 9 - March 29 | Potential student participants discuss application ideas with mentoring organizations
March 29 18:00 UTC | Student application period begins
April 13 18:00 UTC | Student application deadline
May 3 18:00 UTC | Student slot requests due from Org Admins
May 13 18:00 UTC | Student Project selections due from Org Admins
May 17 18:00 UTC | Accepted student projects announced
Community Bonding Period | Students get to know mentors, read documentation, get up to speed to begin working on their projects
June 7 | Coding officially begins!
July 12 18:00 UTC | Mentors and students can begin submitting Phase 1 evaluations
July 16 18:00 UTC | Phase 1 Evaluation deadline
Work Period | Students work on their project with guidance from Mentors
August 16 - 23 18:00 UTC | Final week: Students submit their final work product and their final mentor evaluation
August 23 - 30 18:00 UTC | Mentors submit final student evaluations
August 31 | Final results of Google Summer of Code 2021 announced

[Marketing Materials](https://developers.google.com/open-source/gsoc/resources/marketing) (slide deck, flyers)
[Roles and Responsibilities](https://developers.google.com/open-source/gsoc/help/responsibilities)
[FAQ](https://developers.google.com/open-source/gsoc/faq)

Here is [the application notification email](https://groups.google.com/d/msgid/google-summer-of-code-mentors-list/57994707-4bb0-4cf0-8faa-c1e0a36a38c0n%40googlegroups.com?utm_medium=email&utm_source=footer).

**Comment by LinuxSuRen** [comment]
Here is the project proposal list link

https://shimo.im/docs/gG9hGqPwCpkthrXx/
