### ISSUE TITLE
update the installation and introduction guide in kubeasz

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#285]
Ref: https://github.com/easzlab/kubeasz/blob/master/docs/guide/kubesphere.md

**Comment by Felixnoo** [comment]
> Ref: https://github.com/easzlab/kubeasz/blob/master/docs/guide/kubesphere.md

What kind of update am I supposed to make?

**Comment by FeynmanZhou** [comment]
> > Ref: https://github.com/easzlab/kubeasz/blob/master/docs/guide/kubesphere.md
> 
> What kind of update am I supposed to make?

@Felixnoo Update the introduction and installation guide from KubeSphere v2.1 to v3.0.0. It's out-of-date on kubeasz.

**Comment by FeynmanZhou** [comment]
@Felixnoo Let us know if you have updated the content.

**Comment by Felixnoo** [comment]
> @Felixnoo Let us know if you have updated the content.

OK.

**Comment by Felixnoo** [comment]
@FeynmanZhou I made updates in the guide and submitted a PR[https://github.com/easzlab/kubeasz/pull/968](url).

**Comment by FeynmanZhou** [comment]
@Felixnoo Thanks. It has been merged by Kubeasz. 
BTW, please use `kubesphere.com.cn` in Chinese community instead of `kubesphere.io/zh`.

**Comment by Felixnoo** [comment]
> @Felixnoo Thanks. It has been merged by Kubeasz.
> BTW, please use `kubesphere.com.cn` in Chinese community instead of `kubesphere.io/zh`.

Got it.
