### ISSUE TITLE
Is kubesphere-kubevirt support windows vm?

### ISSUE THREAD

**Issue by gotoworld** [kubesphere/community#288]
Thanks for the kubesphere-kubevirt sharing in yesterday noon, it's wonderful and helpful.

We wonder to know wheather the kubesphere-kubevirt support windows vm,  
or may you provide a sample of kubevirt windows vm pod ?

Thanks a lot.

**Comment by gotoworld** [comment]
Beyond the more security reason for use kubevirt,  support windows vm is the sweets that we expected.

**Comment by FeynmanZhou** [comment]
@gotoworld  Yes, it supports windows.

**Comment by gotoworld** [comment]
> @gotoworld Yes, it supports windows.

Great, Thanks.
