### ISSUE TITLE
[Proposal] Perform a Pre-release and Get a Release Guideline

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/community#292]
## Background

- release process relies on the special people
- release process of release is not clear to the community
- release time can't be evaluated

## Why

We need to do a pre-release, which is used to test the process. At the same time, a pre-release will provide a checklist and guideline for the next release version 3.1.0.

## Benefit

- allow anyone to publish a release, don't need special people
- make the whole process automated, and more efficient
- avoid manual omissions and errors

## Workflows

1. deploy a harbor server for the workflows, e.g harbor.com. 
2. transfer the images from harbor.com/kubespheredev to harbor.com/kubesphere/
3. prepare the release note for the version
4. update readme 、 create a branch、make a  release version  for repositories:  kubesphere、ks-installer、website
5. prepare the pr for the version
6. promote the release in forums、wechat、slack、Twitter、medium...

## Members

@calvinyv 
@zryfish 
@pixiake 
@LinuxSuRen 
@shaowenchen

**Comment by LinuxSuRen** [comment]
Consider not everyone exactly knows the release flow. It will more clear if you can write down the current flow and the expected flow. But don't worry if you can write down all the details. An outline is good enough.

**Comment by shaowenchen** [comment]
It needs to be discussed and done in the next month.
