### ISSUE TITLE
[Proposal] Create a GitHub Team for Every SIG

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/community#293]
## Background

During the discussion phase, issues and pull requests are directly linked to individuals. This is unreasonable. All members of the SIG are responsible for the SIG.

## Benefit

All members of SIG will be notified. This will reduce the burden on individuals and speed up the processing of work. It will also avoid the impact that occurs when someone leaves the community.

## Workflows

1. create a team in https://github.com/orgs/kubesphere/teams, e.g sig-devops
2. add members to sig-devops
3. use @kubesphere/sig-devops replace @shaowenchen 

## Member

@rayzhou2017 
@zryfish 
@FeynmanZhou 
@LinuxSuRen

**Comment by FeynmanZhou** [comment]
Agree. It might be much efficient in community collaboration.

**Comment by LinuxSuRen** [comment]
I can agree more. I would suggest that all people follow this guide. Please make sure to address the relevant team.
/cc @kubesphere/developers

**Comment by shaowenchen** [comment]
done
