### ISSUE TITLE
[Proposal] Setup a new SIG for Metering

### ISSUE THREAD

**Issue by yunkunrao** [kubesphere/community#294]
As metering will be intergrated into KubeSphere as an independent module within toolbox. Metering is based on Prometheus API and provides user with consumption information about the cluster resource. So do we need setup a new SIG for metering or classify it into some other existing SIG?

**Comment by FeynmanZhou** [comment]
> As metering will be intergrated into KubeSphere as an independent module within toolbox. Metering is based on Prometheus API and provides user with consumption information about the cluster resource. So do we need setup a new SIG for metering or classify it into some other existing SIG?

Let me verify it with TOC.

**Comment by FeynmanZhou** [comment]
As I discussed with TOC, @benjaminhuo suggests Metering is supposed to be joined into @kubesphere/sig-observability . How do you think of it?

**Comment by LinuxSuRen** [comment]
Any updates?

**Comment by benjaminhuo** [comment]
No need to setup a new sig for metering, it's part of Observability SIG
