### ISSUE TITLE
[Proposal] A Guide to Contribute Community

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/community#295]
## Background

For someone who wants to contribute, he is confused. 

- How to participate in contributing?
- How to submit Issues?
- How to submit code? 
- How to submit the documentation? 
- How to participate in conferences?

## Benefit

Everyone who enters the community, know how to contribute. 

## Workflows

- Create a list of how to contribute, just like 
    - translate documents
    - create an issue for the bug
    - fix an issue
    - add test unit
    - join a weekly meeting
    - ...
- Provide a workflow to the above list. For example, fixing an issue:
    - accept an issue. You need to reply `let me fix it` to this issue.
    - read the developer doc https://github.com/kubesphere/community/tree/master/developer-guide/development
    - coding to fix. 
    - add unit tests.
    - submit a pr. Please sign off your code.
    - wait for review
    - fix it according to comments of the review
    - get `/lgtm` and `/approve` to merge your code

## Member

@FeynmanZhou 
@zryfish 
@LinuxSuRen 
@shaowenchen 

## Reference

- https://kubesphere.io/contribution/

**Comment by FeynmanZhou** [comment]
Do we need to set up a meeting to discuss the division of our four members?

**Comment by LinuxSuRen** [comment]
Thanks for taking the initiative to have this proposal. I'd like to add something here.

# For the newcomers
It's good to have a place to tell them what they can do exactly. There's an example that we can learn from it. Let me make it be short. We should make a category list. People who have different backgrounds can choose it easily.

## Documentation
We probably should have a meeting with all the current documentation contributors to discuss how to improve all flow.

## Coding
For those who are interested in coding contribution. It will be much more friendly if we can have an issue list that can be searched by the label `newbie-friendly`.

But I don't know how to add the label `newbie-friendly` across the whole KubeSphere GitHub organization. Perhaps we need to put this label into `Prow`. Please comment it here if anyone knows it.

## Testing
TODO

## Event
There's a potential SIG #291 could be the perfect place to gather these people.

In the end, I believe this is an excellent proposal. We highly suggest we move it forward as soon as possible.

**Comment by LinuxSuRen** [comment]
Here is [the link](https://github.com/search?q=user%3Akubesphere+label%3A%22good+first+issue%22+state%3Aopen&type=Issues&ref=advsearch&l=&l=) for the potential new contributors.
