### ISSUE TITLE
[Proposal] Using GitHub Projects to Manage the Process of SIG-DevOps 

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/community#298]
## Background

DevOps consists of a pipeline and s2i, including many repositories. SIG-DevOps can't display the progress and status of work Intuitively.

## Benefit

- GitHub Projects is more friendly to the community
- Everyone can get our progress and participate in it
- Issues from different repositories will be aggregated

## Workflows

- create a project named `SIG-DevOps` or `DevOps Team`
- add columns `In progress`   `To do`   `Done`   `Refused`  `Delay`  to  show the different stages
- review opened issues about DevOps and add them to different stages
- when a new issue comes, deal with it

## Member

@kubesphere/sig-devops

**Comment by LinuxSuRen** [comment]
Agree! All contributors can exactly know the progress instead of a few people. We can create the project on the org level.

**Comment by shaowenchen** [comment]
I will implement it today.

**Comment by LinuxSuRen** [comment]
Please go ahead.

**Comment by shaowenchen** [comment]
I have created the project https://github.com/orgs/kubesphere/projects/3  and add some issues to the different columns.

Please use `/project devops` to add an issue to the project.
