### ISSUE TITLE
The division of technical writers

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#299]
There are many features and components in KubeSphere, each component has a high learning curve. A clear division of labor allows the technical writers to deep dive into the specific domains and be more efficient. From my point of view, I've summarized these directions (domains) for our technical writers to choose from. If there is anything been missed, please add your comment below.

**Mindmap**: https://www.processon.com/view/link/600f7abe079129045d37d571#map

![image](https://user-images.githubusercontent.com/40452856/105833012-97083d00-6003-11eb-92e2-9f2983b0c327.png)

Let's schedule a meeting to discuss the division.

**Comment by FeynmanZhou** [comment]
/cc @kubesphere/sig-docs 

is inviting you to a scheduled Zoom meeting.

Topic: KubeSphere SIG-Docs Meeting
Time: Jan 26, 2021 04:00 PM Beijing, Shanghai

Join Zoom Meeting
https://us02web.zoom.us/j/84437946426?pwd=ZVEwQ1JLaVJPVUlPZko4bXIrd2hyUT09

Meeting ID: 844 3794 6426
Passcode: 633120

**Comment by Sherlock113** [comment]
Sure. With a specific AOE, everyone can focus on the topic to write guides and blogs or record videos.

**Comment by Sherlock113** [comment]
I select Installation, Service Mesh and Storage. Will keep a close eye on these three aspects.

**Comment by Felixnoo** [comment]
I select DevOps, App Store and Multi-cluster.

**Comment by Patrick-LuoYu** [comment]
I select Network, Edge Computing and Multi-tenancy

**Comment by FeynmanZhou** [comment]
Let me pick KubeSphere Introduction, KubeSphere Observability and KubeSphere Virtualization.

**Comment by FeynmanZhou** [comment]
Done.
