### ISSUE TITLE
[Proposal] Create a git repo: artwork 

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#300]
As we have many KubeSphere-related images, logos, icons, and files that need to be stored, it will be easy to find them if there is an independent git repo for artwork. 

Example: [cncf/artwork](https://github.com/cncf/artwork).

**Comment by zryfish** [comment]
Agree

**Comment by FeynmanZhou** [comment]
Hi @zryfish @LinuxSuRen @kubesphere/sig-advocacy-and-outreach ,

The artwork repository has been created, we can migrate all KubeSphere-related logos and artworks from the Community repo to the artwork repo.

**Comment by LinuxSuRen** [comment]
One thing needs to be careful. Rewrite the image link if was referenced by the current repository.
