### ISSUE TITLE
Set up KubeSphere Community Users Committee of Shanghai and Hangzhou

### ISSUE THREAD

**Issue by faweizhao26** [kubesphere/community#329]
We are going to set up KubeSphere Community Users Committee of Shanghai and Hangzhou.
About this committee, you can read the [md](https://hackmd.io/@zhaofawei/SkTsjW-vu) to learn more information.
Besides, if you have any good idea, you can edit this md and add your thoughts.

**Comment by LinuxSuRen** [comment]
I guess we already have it.

/close
