### ISSUE TITLE
REQUEST: New membership for Akhil

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#335]
## GitHub Username
@[Akhil](https://github.com/akhilerm)

## Requirements

- [x] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [x] Finish one or more features
- [x] Sponsored by two members of the SIG and approved by the lead of the SIG
- [x] Help review PR from other contributors

## Sponsors

@FeynmanZhou 
@pixiake 

## List of contributions to the KubeSphere project

https://github.com/kubesphere/kubekey/pull/382
https://github.com/kubesphere/kubekey/pull/533

**Comment by zheng1** [comment]
LGTM

**Comment by wansir** [comment]
LGTM

**Comment by LinuxSuRen** [comment]
@Akhil already was a member of the KubeSphere community. 
![image](https://user-images.githubusercontent.com/1450685/128445462-863515f9-07a0-4862-903a-681fb6176efb.png)

/close
