### ISSUE TITLE
REQUEST: New membership for Bojan

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#336]
## GitHub Username
@[Bojan](https://github.com/bojand)

## Requirements

- [x] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [x] Finish one or more features
- [x] Sponsored by two members of the SIG and approved by the lead of the SIG
- [x] Help review PR from other contributors

## Sponsors

@FeynmanZhou 
@benjaminhuo 

## List of contributions to the KubeSphere project

Add syslog output to Fluentbit-operator: https://github.com/kubesphere/fluentbit-operator/pull/49

**Comment by zheng1** [comment]
lgtm

**Comment by LinuxSuRen** [comment]
@bojand already was a member of the KubeSphere community. 
![image](https://user-images.githubusercontent.com/1450685/128445581-0ecc2b18-961f-4404-a8db-f371701ce4d3.png)

/close
