### ISSUE TITLE
REQUEST: New membership for Dhruv

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#344]
## GitHub Username
@[Dhruv Kela](https://github.com/keladhruv)

## Requirements

- [x] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [x] Finish one or more features
- [x] Sponsored by two members of the SIG and approved by the lead of the SIG
- [x] Help review PR from other contributors

## Sponsors

@wanjunlei 
@benjaminhuo 

## List of contributions to the KubeSphere project

- Add client to fluentbit-operator: https://github.com/kubesphere/fluentbit-operator/pull/51
- As an approver of the KubeSphere proposal: https://github.com/digitalocean/marketplace-kubernetes/issues/213

**Comment by zheng1** [comment]
LGTM

**Comment by benjaminhuo** [comment]
LGTM

**Comment by LinuxSuRen** [comment]
@keladhruv already was a member of the KubeSphere community. 
![image](https://user-images.githubusercontent.com/1450685/128445542-38191145-2107-4a2f-bad0-124af19bdff1.png)

/close
