### ISSUE TITLE
cannot visit the docs website.

### ISSUE THREAD

**Issue by longzhixin** [kubesphere/community#348]
cannot visit the docs website.  
https://kubesphere.io/zh/docs/faq/observability/byop/

![image](https://user-images.githubusercontent.com/13051065/121460239-34767300-c9df-11eb-88da-76fd235e50c0.png)
503 Service Temporarily Unavailable
nginx/1.15.10

**Comment by FeynmanZhou** [comment]
It has been fixed and recovered.
