### ISSUE TITLE
REQUEST: New membership for lshmouse

### ISSUE THREAD

**Issue by pixiake** [kubesphere/community#349]
## GitHub Username
@lshmouse
 
## Requirements
* [x]  Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
* [x]  Finish one or more features
* [x]  Sponsored by two members of the SIG and approved by the lead of the SIG
* [x]  Help review PR from other contributors
 
## Sponsors
@FeynmanZhou
@pixiake

## List of contributions to the KubeSphere project
https://github.com/kubesphere/kubekey/pull/542
https://github.com/kubesphere/kubekey/pull/544
https://github.com/kubesphere/kubekey/pull/547
https://github.com/kubesphere/image-sync-config/pull/7

**Comment by LinuxSuRen** [comment]
hi @lshmouse, thanks for your efforts. And welcome to be a member of the KubeSphere community. We all look forward to seeing more voice and innovation from you.

**Comment by FeynmanZhou** [comment]
Support. Welcome onboard! @lshmouse

**Comment by LinuxSuRen** [comment]
@lshmouse already was a member of the KubeSphere community. 
![image](https://user-images.githubusercontent.com/1450685/128445391-9e95e7a7-240f-4889-89b2-7c00b8e7efb1.png)

/close
