### ISSUE TITLE
Community Events CFP in Aug

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#353]
There are some great community events and conferences that are open to CFP this month, we can call for our maintainers, partners, and users to submit the proposals to these events and conferences. Please help us to organize them in the community.

- [x] [OpenInfra Days China 2021](https://pages.segmentfault.com/openinfra-2021)
- [x] [Open Source Summit China 2021](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/program/cfp-oss/)
- [ ] [COSCON 2021 | 中国开源年会](http://coscon.kaiyuanshe.cn/#)
- [ ] [DoK Day | KubeCon NA 2021](https://dok.community/dok-day/)

**Comment by faweizhao26** [comment]
I think this issue is out of date. So I close it now.
