### ISSUE TITLE
kubesphere katacoda tutorials 

### ISSUE THREAD

**Issue by AbdelouahabMbarki** [kubesphere/community#355]
As there are a lot of open source projects in the cnf land scape using katacoda tutorials to make it easier for the community to get started with the tool and learn more about it, it will be great to have tutorials for kubesphere too to test different scenarios and get more familiar with it.

useful links : 
- [ katacoda scenario  examples](https://github.com/katacoda/scenario-examples)
- [katacoda community doc](https://www.katacoda.community/welcome.html)

**Comment by AbdelouahabMbarki** [comment]
i found that there is two solution for this

**the first one:**
is  where we can use the Kubernetes Cluster 1.18 (Pre-configured) which is free and add a Storage class to it like [openebs](https://openebs.io/) and  then install  kubesphere on it  using [ks-installer](https://github.com/kubesphere/ks-installer) . It works, but we have to wait for the setup of kubesphere and the Storage class which can take up to 15-20 min.

**the second one:**
is by creating a [custom-environment](https://www.katacoda.community/custom-environment.html#creating-custom-environment) with all the tools pre installed this will eliminate install time, but it's a paid solution

**Comment by FeynmanZhou** [comment]
@AbdelouahabMbarki  Really appreciate your suggestion! As for the first solution, could you help us to write a brief guide to introduce how to install KubeSphere on the KataCoda environment? It can be an optional way for the novices who are really want to get started even they don't have VMs.

As for the second solution, it could be supported in the future, it requires long progress in my opinion.

**Comment by AbdelouahabMbarki** [comment]
what do you think about this scenario https://www.katacoda.com/h1rkul2/scenarios/kubsphere02 what can be improved

**Comment by LinuxSuRen** [comment]
It's great. IMO, we can put the link somewhere to let people know it. And if you have git repo for this. We can collaborate with each other. For example, we can put it in https://github.com/kubesphere-sigs/ for now.

**Comment by FeynmanZhou** [comment]
👍 I will try it later.

**Comment by FeynmanZhou** [comment]
I have installed KubeSphere on K8s successfully within around 20+ minutes! Will this scenario link be permanently valid? It seems that the Kubernetes environment is only reserved for half an hour only, it will be destroyed after that period, right?

![image](https://user-images.githubusercontent.com/40452856/131313002-afe124aa-fd05-4ef2-b6d3-a3aee1682765.png)

**Comment by AbdelouahabMbarki** [comment]
Kubernetes cluster can be reserved up to  60 minutes then the environment will be expired so you have to refresh the page again

**Comment by AbdelouahabMbarki** [comment]
@LinuxSuRen  i will submit it to kubesphere-sigs so we can collaborate on it more

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen i will submit it to kubesphere-sigs so we can collaborate on it more

I'm not sure if you have the permission to create a repo. Please tell me the name if you cannot.

**Comment by FeynmanZhou** [comment]
> Kubernetes cluster can be reserved up to 60 minutes then the environment will be expired so you have to refresh the page again

Will this scenario link be permanently valid?

**Comment by AbdelouahabMbarki** [comment]
@FeynmanZhou  yes i doesn't change ,  i will send a  new link after we put it in kubesphere-sigs

**Comment by LinuxSuRen** [comment]
It is online. See https://www.katacoda.com/kubesphere

Thanks @FeynmanZhou @AbdelouahabMbarki 

/close

**Comment by FeynmanZhou** [comment]
> It is online. See https://www.katacoda.com/kubesphere
> 
> Thanks @FeynmanZhou @AbdelouahabMbarki
> 
> /close

Thanks @AbdelouahabMbarki 's effort!

BTW, could you help us to add the katacoda scenario link to the [README](https://github.com/kubesphere/kubesphere#quick-start)? It would bring more visibility to this scenario.
