### ISSUE TITLE
REQUEST: New membership for @wenhuwang

### ISSUE THREAD

**Issue by wenhuwang** [kubesphere/community#364]
## GitHub Username

[@wenhuwang](https://github.com/wenhuwang)

## Requirements

- [x] -  Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [x] -  Finish one or more features
- [x] -  Sponsored by two members of the SIG and approved by the lead of the SIG
- [x] -  Help review PR from other contributors

# Sponsors

[@FeynmanZhou](https://github.com/FeynmanZhou)
[@pixiake](https://github.com/pixiake)

# List of contributions to the KubeSphere project

- PRs reviewed / authored

​       https://github.com/kubesphere/kubesphere/pulls?q=is%3Apr+author%3Awenhuwang

   - ​[kubesphere/kubesphere#4164](https://github.com/kubesphere/kubesphere/pull/4164)

   - ​[kubesphere/kubesphere#4121](https://github.com/kubesphere/kubesphere/pull/4121)

​      https://github.com/kubesphere/ks-installer/pulls?q=is%3Apr+author%3Awenhuwang

  - ​[kubesphere/ks-installer#1533](https://github.com/kubesphere/ks-installer/pull/1533)

  - [kubesphere/ks-installer#1253](https://github.com/kubesphere/ks-installer/pull/1253)

**Comment by liangyuanpeng** [comment]
W00t! +1 from me! 🎉

**Comment by FeynmanZhou** [comment]
+1 support! 

cc @kubesphere/toc

**Comment by zheng1** [comment]
+1

**Comment by LinuxSuRen** [comment]
@wenhuwang already be a member of the community. I'm going to close this issue. Welcome to join the community!

/close

![image](https://user-images.githubusercontent.com/1450685/148649768-f9970fb9-a0a8-4b05-9e4b-a2f2c13227a0.png)
