### ISSUE TITLE
[Nominations Open]  KubeSphere Ambassador Award 2021 🏆

### ISSUE THREAD

**Issue by faweizhao26** [kubesphere/community#365]
This issue is to receive nominations for KubeSphere Ambassador Award 2021.

To nominate someone（it could be you）, reply to this issue with the following:

- Full name of the person you’re nominating.
- Short description of their contributions to KubeSphere and why they should win.

**Attention**：If your name is already in this [document](https://shimo.im/sheets/YC3ypTk3wDQYJYRQ/MODOC/), you don't need to reply this issue.

We will be presenting  awards on September 16th for the first time.

**Comment by 912988434** [comment]
Shuai Li
Spread and share the use of kubesphere, introduce how to minimize the installation of kubespere and use the existing proemtheus for monitoring and display, and how to use OIDC Identity Provider (dex+gitlab) for user authentication.

- https://mp.weixin.qq.com/s/GbeyC3RH0EYCCrAHHOPrjg
- https://mp.weixin.qq.com/s/TzDwReLHDsuoIfclOa29bQ

**Comment by LinuxSuRen** [comment]
I guess this was done according to the description. I'm going to close it.
/close
