### ISSUE TITLE
[Nominations Open] KubeSphere Contributor Award 2021 🏆

### ISSUE THREAD

**Issue by faweizhao26** [kubesphere/community#367]
This issue is to receive nominations for KubeSphere Contributor Award 2021.

To nominate someone（it could be you）, reply to this issue with the following:

- Full name of the person you’re nominating.
- Short description of their contributions to KubeSphere and why they should win.

**Attention**：If your name is already in this [document](https://shimo.im/sheets/RgKwRxtxT3PDvHTj/MODOC/), you don't need to reply this issue.

We will be presenting  awards on September 16th for the first time.

**Comment by wenhuwang** [comment]
Fullname: wenhuwang
description:  I contributed to the kubesphere and ks-installer project.

**Comment by liulangwa** [comment]
前段时间调研k8s管理平台，选中了kubesphere，最近把部署遇到的问题修复提交了，以后也会给大家推荐这个棒棒的平台。

**Comment by LeonDevLifeLog** [comment]
kubesphere/helm-charts#197
kubesphere/helm-charts#193
kubesphere/ks-devops#354

it's myself.

report a high priority security issue and fix it. :sweat_smile:

Is that possible to earn a award?

**Comment by LinuxSuRen** [comment]
I guess this was done according to the description. I'm going to close it.
/close
