### ISSUE TITLE
[Nominations Open] KubeSphere Member Award 2021 🏆

### ISSUE THREAD

**Issue by faweizhao26** [kubesphere/community#368]
This issue is to receive nominations for KubeSphere Member Award 2021.

To nominate someone（it could be you）, reply to this issue with the following:

- Full name of the person you’re nominating.
- Short description of their contributions to KubeSphere and why they should win.

**Attention**：If your name is already in this [document](https://shimo.im/sheets/T86qhgVyQRKtWQpV/MODOC/), you don't need to reply this issue.

We will be presenting  awards on September 16th for the first time.

**Comment by wenhuwang** [comment]
I'd like to nominate myself([wenhu wang](https://github.com/wenhuwang)) for this award.

I have been using the Kubesphere project for a year and a half, starting from v2.1 to v3.2. In the process of using kubesphere, I also like to take time to troubleshoot and share with kubesphere community users when encountering problems, as well as exchange issues in the forum. Some issues that need to be fixed were also submitted to the community in time, such as fixing the kubeedge problem of the ks-installer project deployment and upgrading the ingress-controller version. Also made contributions such as upgrading the ingress api version in kubesphere through communicating with the community. I hope to join the kubesphere community and learn from everyone.

**Comment by LinuxSuRen** [comment]
I guess this was done according to the description. I'm going to close it.
/close
