### ISSUE TITLE
[Nominations Open] KubeSphere Talented Speaker Award 2021 🏆

### ISSUE THREAD

**Issue by faweizhao26** [kubesphere/community#369]
This issue is to receive nominations for KubeSphere Talented Speaker Award for the first half of 2021.

To nominate someone（it could be you）, reply to this issue with the following:

- Full name of the person you’re nominating.
- Short description of their contributions to KubeSphere and why they should win.

**Attention**：If your name is already in this [document](https://shimo.im/sheets/rKGRPXCGTpWWRrrp/MODOC/), you don't need to reply this issue.

We will be presenting  awards on September 16th for the first time.

**Comment by LinuxSuRen** [comment]
I guess this was done according to the description. I'm going to close it.
/close
