### ISSUE TITLE
REQUEST: New membership for AbdelouahabMbarki

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/community#372]
### GitHub Username

@AbdelouahabMbarki

### Requirements

- [X] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [X] Finish one or more features
- [X] Sponsored by two members of the SIG and approved by the lead of the SIG
- [X] Help review PR from other contributors

### Sponsor 1

@linuxsuren

### Sponsor 2

@JohnNiang

### List of contributions to the Kubernetes project

- [kubesphere-sigs/katacoda-scenarios](https://github.com/kubesphere-sigs/katacoda-scenarios/pulls?q=is%3Apr+author%3AAbdelouahabMbarki)
- [kubesphere/ks-devops](https://github.com/kubesphere/ks-devops/pulls?q=is%3Apr+is%3Aclosed+author%3AAbdelouahabMbarki)

![image](https://user-images.githubusercontent.com/1450685/138993967-6580d8c2-2354-4ef8-812a-449170740b26.png)
![image](https://user-images.githubusercontent.com/1450685/138993986-cbe448b2-681f-4953-8125-5e1e0870d683.png)

**Comment by FeynmanZhou** [comment]
I have sent the member invitation to @AbdelouahabMbarki.

**Comment by AbdelouahabMbarki** [comment]
Thanks guys i appreciate it

**Comment by FeynmanZhou** [comment]
Invited and closed
