### ISSUE TITLE
REQUEST: New membership for mangoGoForward

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/community#374]
### GitHub Username

@mangoGoForward

### Requirements

- [X] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [X] Finish one or more features
- [X] Sponsored by two members of the SIG and approved by the lead of the SIG
- [X] Help review PR from other contributors

### Sponsor 1

@linuxsuren

### Sponsor 2

@harrisonliu5

### List of contributions to the Kubernetes project

@mangoGoForward is a very active contributor. He already explored several projects. This is an excellent example for all potential KubeSphere members. The best way is to give it a try.

Below are parts of his PRs:

- https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/30
- https://github.com/kubesphere/ks-devops/pull/328
- https://github.com/kubesphere/console/pull/2575
- https://github.com/kubesphere/console/pull/2500
- https://github.com/kubesphere/console/pull/2497
- https://github.com/kubesphere/console/pull/2480
- https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/39
- https://github.com/kubesphere/helm-charts/pull/185

I really really hope @mangoGoForward could learn open-source and tech skills from this journey.

If you want to know more from me, I'd like to say that reviewing and creating something are all very important. You can help others to review their code (or documentation) if you have free time.

**Comment by mangoGoForward** [comment]
I'm appreciate and  will keep it up, thanks your advice.

**Comment by harrisonliu5** [comment]
I am very happy to have new members join us. It is my honor to be your sponsor. I hope you can enjoy it and gain something and welcome to join us.

**Comment by mangoGoForward** [comment]
> I am very happy to have new members join us. It is my honor to be your sponsor. I hope you can enjoy it and gain something and welcome to join us.

Thanks.

**Comment by FeynmanZhou** [comment]
Invited and closed.
