### ISSUE TITLE
REQUEST: New membership for chaunceyjiang

### ISSUE THREAD

**Issue by pixiake** [kubesphere/community#379]
### GitHub Username

@chaunceyjiang

### Requirements

- [X] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [X] Finish one or more features
- [X] Sponsored by two members of the SIG and approved by the lead of the SIG
- [ ] Help review PR from other contributors

### Sponsor 1

@pixiake @24sama 

### Sponsor 2

@FeynmanZhou

### List of contributions to the Kubernetes project

https://github.com/kubesphere/kubekey/pull/887
https://github.com/kubesphere/kubekey/pull/880
https://github.com/kubesphere/kubekey/pull/850
https://github.com/kubesphere/kubekey/pull/841

**Comment by 24sama** [comment]
+1 support

**Comment by benjaminhuo** [comment]
+1

**Comment by FeynmanZhou** [comment]
@chaunceyjiang Invited. Thank you all!
