### ISSUE TITLE
Add KubeSphere Helm Chart to the Civo Marketplace

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#380]
Civo.com is introducing the world's first managed K3s service and the [Civo marketplace](https://github.com/civo/kubernetes-marketplace) is a PaaS to enable users to install apps on Civo Cloud with one click. We are preparing to add KubeSphere Helm Chart to the Civo marketplace. If you are interested in helping us to make it happen, please leave your comments below.

**Comment by FeynmanZhou** [comment]
> /assign

Thanks for @mangoGoForward 's help. If you need any materials or help, feel free to let me know.

**Comment by mangoGoForward** [comment]
> Thanks for @mangoGoForward 's help. If you need any materials or help, feel free to let me know.

We need a png logo.

**Comment by FeynmanZhou** [comment]
> > Thanks for @mangoGoForward 's help. If you need any materials or help, feel free to let me know.
> 
> We need a png logo.
<img width="1383" alt="kubesphere-logo" src="https://user-images.githubusercontent.com/40452856/148340348-8080aa96-23f5-4eab-9ea4-5a536b915a6b.png">

**Comment by mangoGoForward** [comment]
The logo seems does not need text `KUBESPHERE`, we can set `name`, it will displayed in web interface alongside the logo.png.

**Comment by FeynmanZhou** [comment]
<img width="198" alt="kubesphere-logo-only" src="https://user-images.githubusercontent.com/40452856/148341685-119b3ae7-73c5-44f2-a722-ddbcd7be6fe3.png">

**Comment by mangoGoForward** [comment]
fixed #civo/kubernetes-marketplace#290

**Comment by FeynmanZhou** [comment]
Completed
