### ISSUE TITLE
REQUEST: New membership for tanguofu

### ISSUE THREAD

**Issue by tanguofu** [kubesphere/community#383]
### GitHub Username

tanguofu

### Requirements

- [X] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [X] Finish one or more features
- [X] Sponsored by two members of the SIG and approved by the lead of the SIG
- [X] Help review PR from other contributors

### Sponsor 1

pixiake

### Sponsor 2

sama24

### List of contributions to the Kubernetes project

https://github.com/kubesphere/kubekey/pull/866
https://github.com/kubesphere/kubekey/pull/870
https://github.com/kubesphere/kubekey/pull/882
https://github.com/kubesphere/kubekey/pull/896
https://github.com/kubesphere/kubekey/pull/902

**Comment by FeynmanZhou** [comment]
support!

/cc @kubesphere/toc

**Comment by pixiake** [comment]
support!

**Comment by zheng1** [comment]
support!

**Comment by LinuxSuRen** [comment]
+1 from me

@tanguofu thanks for your contribution. Let's build the community together.

**Comment by FeynmanZhou** [comment]
Invitation sent! Welcome to join the community. @tanguofu
