### ISSUE TITLE
Request to retire those in-active SIGs

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/community#386]
There are over 15 SIGs you can find from the [website page](https://kubesphere.com.cn/contribution/). But as we can see, there are only four SIGs are active for a very long time (over 1 year).

* [DevOps SIG](https://github.com/kubesphere/community/tree/master/sig-devops)
* [Advocate and outreach SIG](https://github.com/kubesphere/community/tree/master/sig-advocacy-and-outreach)
* [Observability SIG](https://github.com/kubesphere/community/tree/master/sig-observability)
* [Serverless SIG](https://github.com/kubesphere/community/tree/master/sig-serverless)

This will make the newcomers feel confused. They might think that how to involve other SIGs, do they still exist or not?

/cc @kubesphere/toc 
/cc @kubesphere/sig-advocacy-and-outreach

**Comment by FeynmanZhou** [comment]
IMO, I agree to retire other inactive SIGs or provide a choice to combine them with the current SIGs. For example, Edge SIG can be combined into Observability SIG as an Observability & Edge working group.  

If we don't see any proactive ideas from those inactive SIGs, then we could mark them to retire.

**Comment by LinuxSuRen** [comment]
Some SIGs are quite important. It's good for the community if someone can help to run it. For instance:

* [Installation SIG](https://github.com/kubesphere/community/tree/master/sig-installation)
  * Installation is the first step for every newcomer.
* [Console SIG](https://github.com/kubesphere/community/tree/master/sig-console)
  * IMO, the frontend might be easy for people to try their first contribution. I think it could be easy to maintain this SIG be active.

**Comment by LinuxSuRen** [comment]
Considering there is no response for a long time. I'm going to close this.
