### ISSUE TITLE
REQUEST: New membership for Arhell

### ISSUE THREAD

**Issue by Arhell** [kubesphere/community#394]
### GitHub Username

@Arhell

### Requirements

- [X] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [X] Finish one or more features
- [X] Sponsored by two members of the SIG and approved by the lead of the SIG
- [X] Help review PR from other contributors

### Sponsor 1

@FeynmanZhou

### Sponsor 2

@weili520

### List of contributions to the Kubernetes project

https://github.com/kubesphere/website/pulls/Arhell
https://github.com/kubesphere/website/pulls?q=is%3Apr+author%3AArhell+is%3Aclosed

https://github.com/kubesphere/website/issues/created_by/Arhell
https://github.com/kubesphere/website/issues?q=is%3Aissue+author%3AArhell+is%3Aclosed

https://github.com/kubesphere/website

**Comment by FeynmanZhou** [comment]
Support!

**Comment by wansir** [comment]
Support +1

**Comment by benjaminhuo** [comment]
+1 binding

**Comment by weili520** [comment]
Support + 1
