### ISSUE TITLE
REQUEST: New leader for a User Group in new city

### ISSUE THREAD

**Issue by ezcmd** [kubesphere/community#412]
### GitHub ID

@ezteki

### City Name

Guang Zhou

### Prerequisites for new city

- [X] The city must be initiated by at least one member of the KubeSphere community who has been active in the last six months as a leader.

### Contact information

wechat: hsdtsyl

### Reason to create a User Group for a new city

1. GuangDong is `The Second` City where community members are
2. `Prevention of COVID-19` of Guangzhou is Fully in Control, compare with Shenzhen
3. The partners of community where they are is here

### Requirements

- [X] The leader is required to ensure that at least one offline activity is organized each year in his city (with the exception of special circumstances such as epidemics)
- [X] If a leader is temporarily or permanently unable to organize an offline event in their city for any reason, they need to submit a request to the community to recommend a new leader, or ask the community to recommend a new leader. If no one is eventually able to organize an event, the city is set to inactive until a new active member appears.

### Planning for the future of new city

1. Interactive with upstream leadership for more frequently activities if `Env Allows`
2.co-operate with other city to publish `video` or event `audio` arts;
3.organize members for more outputs: doc, broadcast

**Comment by FeynmanZhou** [comment]
Support! It's glad to see @ezteki for being a User Group leader in Guangzhou.

**Comment by faweizhao26** [comment]
Support！

**Comment by yangchuansheng** [comment]
Support! Hope @ezteki can add to the great cloud native business in Guangzhou.

**Comment by faweizhao26** [comment]
I think this issue is out of date. So I close it now.
