### ISSUE TITLE
REQUEST: New membership for zhaohuiweixiao

### ISSUE THREAD

**Issue by zhaohuiweixiao** [kubesphere/community#416]
### GitHub Username

@zhaohuiweixiao

### Requirements

- [X] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [X] Finish one or more features
- [X] Sponsored by two members of the SIG and approved by the lead of the SIG

### Sponsor 1

@harrisonliu5

### Sponsor 2

@weili520

### List of contributions to the Kubernetes project

https://github.com/kubesphere/console/pulls?q=is%3Apr+author%3Azhaohuiweixiao+is%3Aclosed

**Comment by weili520** [comment]
Support + 1

**Comment by harrisonliu5** [comment]
support

**Comment by zheng1** [comment]
Invited
