### ISSUE TITLE
REQUEST: New membership for fsl

### ISSUE THREAD

**Issue by fengshunli** [kubesphere/community#418]
### GitHub Username

@fengshunli

### Requirements

- [X] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [X] Finish one or more features
- [X] Sponsored by two members of the SIG and approved by the lead of the SIG
- [X] Help review PR from other contributors

### Sponsor 1

@weili520

### Sponsor 2

@pixiake 

### List of contributions to the Kubernetes project

PRs reviewed / authored:
https://github.com/kubesphere/kubesphere/pull/5463
https://github.com/kubesphere/ks-installer/pull/2155
https://github.com/kubesphere/ks-installer/pull/2156

Issues authored:
https://github.com/kubesphere/kubesphere/issues/5415
https://github.com/kubesphere/ks-installer/issues/2053

Issues responded to:

**Comment by fengshunli** [comment]
@wansir @pixiake help me reply

**Comment by calvinyv** [comment]
Glad to meet you, @fengshunli, this is the product manager of KubeSphere. and big thanks to you for these contributions, all these improvements from contributors worldwide make the KubeSphere community better and better. However, as a potential candidate for KubeSphere member, we think the above PRs could not evaluate as '[notable](https://github.com/kubesphere/community/blob/master/ROLES.md#kubesphere-community-roles)' level, a best practice to become KubeSphere member is filter the issues which are marked as 'good first issue' and start with them, also you could talk with your sponsor to see which feature/issue is the suitable one.
Really appreciate your contribution and expect to see a new KubeSphere member in the near future.

**Comment by fengshunli** [comment]
@calvinyv fluent-operator also has a lot of contributions, can these prs be added? see  https://github.com/fluent/fluent-operator/pulls?q=is%3Apr+author%3Afengshunli+

**Comment by faweizhao26** [comment]
Thanks for your contribution. I think this issue had  lose its effectiveness. So i will close it. Welcome to submit a new application when you meet the requirements.
