### ISSUE TITLE
REQUEST: New membership for zaunist

### ISSUE THREAD

**Issue by zaunist** [kubesphere/community#420]
### GitHub Username

zaunist

### Requirements

- [X] Active contribution to the project. Contributed at least one notable PR to a specific SIG codebase within half a year
- [X] Finish one or more features
- [X] Sponsored by two members of the SIG and approved by the lead of the SIG
- [X] Help review PR from other contributors

### Sponsor 1

@mangoGoForward

### Sponsor 2

@123liubao

### List of contributions to the Kubernetes project

 PRs:
- https://github.com/kubesphere/website/pull/2849
- https://github.com/kubesphere/kubekey/pull/1443
- https://github.com/kubesphere/kubekey/pull/1396
- https://github.com/kubesphere/kubesphere/pull/5084
- https://github.com/kubesphere/kubesphere/pull/5072

Issues:
- https://github.com/kubesphere/kubekey/issues/1432

**Comment by 123liubao** [comment]
+1 support！

**Comment by zheng1** [comment]
invited
