### ISSUE TITLE
Application: 2023 Ambassadorship Program Application berkeucyildiz17

### ISSUE THREAD

**Issue by berkeucyildiz17** [kubesphere/community#435]
### GitHub Username

berkeucyildiz17

### Name

Berke

### Surname

Üçyıldız

### Email

berkeucyildiiz@gmail.com

### Social Media and Other Links About You

https://www.linkedin.com/in/berke-%C3%BC%C3%A7y%C4%B1ld%C4%B1z-7279b921b/
https://twitter.com/UcyildizBerke
https://medium.com/@berkeucyildiiz

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [ ] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [X] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### How do you plan to contribute to the future of KubeSphere if you don't have enough requirements?

I am willing to attend and support community days and promote the kubesphere to other people at events so that it can become more widely known.

### Links and other resources to share with us about the requirements.

https://www.linkedin.com/in/berke-%C3%BC%C3%A7y%C4%B1ld%C4%B1z-7279b921b/
https://twitter.com/UcyildizBerke
https://medium.com/@berkeucyildiiz
https://medium.com/@berkeucyildiiz/linux-virtualization-and-virtual-machine-18a09f1321a3
https://www.linkedin.com/posts/berke-%C3%BC%C3%A7y%C4%B1ld%C4%B1z-7279b921b_community-cloud-kubernetes-activity-7077317842810847233-WpZP?utm_source=share&utm_medium=member_desktop

### What do you think about Cloud Native? What type of experiences have you had before?

Cloud Native is a modern approach where applications are designed to be efficient and scalable in cloud environments. 
I took part in the KCD event, which was an event of CNCF, about Cloud native and I support their projects in Turkey.

### What does KubeSphere mean to you?

KubeSphere is an open-source Kubernetes platform, facilitating cloud-based application management. It can be preferred according to the need, taking into account the advantages and disadvantages.

### What are your plans after becoming an Ambassador?

Community and Awareness Raising: As KubeSphere ambassador, I plan to work actively to raise awareness of the project and contribute to the growth of the community I plan to improve by speaking at webinars, conferences and events, promoting KubeSphere and sharing experiences among users

Contribution and Development: As an Ambassador I can contribute to open source projects to add new features, fix bugs and respond to community requests

### Anything you want to talk about?

Thanks

**Comment by calvinyv** [comment]
Berke, welcome to join KubeSphere community

**Comment by berkeucyildiz17** [comment]
Hi, I'm so excited to join

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @calvinyv @faweizhao26

**Comment by halil-bugol** [comment]
I know Berke. Berke is a student who has just finished school. and he helped us a lot during KCD. But I think it needs more time to become an ambassador. I recommend that he create more content about KubeSphere this year and then get elected next year.

**Comment by faweizhao26** [comment]
I agree with halil.

**Comment by calvinyv** [comment]
+1
@berkeucyildiz17 hope to work with you in KubeSphere Community
