### ISSUE TITLE
Application: 2023 Ambassadorship Program Application enesurkmezz

### ISSUE THREAD

**Issue by EnesUrkmezz** [kubesphere/community#436]
### GitHub Username

enesurkmezz

### Name

Enes

### Surname

Ürkmez

### Email

enessurkmez@gmail.com

### Social Media and Other Links About You

https://www.linkedin.com/in/enesurkmez/

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [ ] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [X] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### How do you plan to contribute to the future of KubeSphere if you don't have enough requirements?

Documentation Improvement: I can contribute to the KubeSphere project by creating comprehensive, up-to-date, and user-friendly documentation. By writing guides, tutorials, and examples, I can help other users understand and utilize KubeSphere more effectively.

Bug Reporting and Fixing: I will identify and report critical bugs to ensure the project's health. If possible, I can also contribute to fixing these issues.

Feature Development: Based on community feedback and requirements, I can propose and discuss new features for KubeSphere. Implementing these features will enhance KubeSphere's capabilities and make it more user-friendly for various scenarios.

Testing and Quality Assurance: I can actively participate in the testing process to ensure the platform's stability and reliability. Testing new releases, verifying bug fixes, and running various test scenarios will be part of my contributions.

Community Support: By engaging with the KubeSphere community through forums, mailing lists, or chat channels, I can provide support to other users. Answering questions and assisting users will help foster the growth of the project.

Code Reviews: I will review code submissions from other contributors to maintain the codebase's quality and security.

Integration with Other Projects: I can contribute to integrating KubeSphere with other relevant projects, expanding its ecosystem, and delivering more value to users.

### Links and other resources to share with us about the requirements.

![A05A9857](https://github.com/kubesphere/community/assets/101511733/0f1719f7-fe13-4a6b-b7cf-a7dd512ac764)

### What do you think about Cloud Native? What type of experiences have you had before?

I don't have much experience with Cloud Native, but I'm interested in the subject. I know we are using cloud native when using KubeSphere. I know that Cloud Native means developing applications with modern technologies and running them in the cloud. I learned that we do this to ensure applications are flexible, scalable and reliable by making the most of the advantages of cloud computing infrastructure.

With the microservice architecture, we can divide the applications into small parts and manage these parts independently. Thanks to container technologies, we can isolate applications and make them portable. We can also provide automated management of applications thanks to orchestration tools such as Kubernetes.

I think the benefits of the Cloud Native approach include scalability, fast deployment, high availability and efficient resource use. It can also provide us with error handling and flexibility to switch between different cloud providers.

It is important for me to get help from resources and experts to learn more about the subject and gain experience. I think I can improve myself by practicing to better understand Cloud Native principles.

### What does KubeSphere mean to you?

KubeSphere is a very valuable technology to me and it is a great opportunity for me to work with it. KubeSphere is a comprehensive Kubernetes platform that allows users to more effectively manage Kubernetes-based applications. Using KubeSphere, our company simplifies application deployment, monitoring and updates, thus providing a better experience for our customers.

I see KubeSphere as a technology that moves our business into the future. Because more and more companies and developers are trying to make their applications more flexible and scalable by adopting Cloud Native principles. KubeSphere plays an important role in this transformation process by bringing together modern approaches such as microservice architecture, container technologies and Kubernetes.

All these features enable KubeSphere to contribute to its users and our business, and I hope it will play an important role in our future projects as well. I believe KubeSphere will continue to evolve and grow, and working with this technology is an exciting experience for me.

### What are your plans after becoming an Ambassador?

As a KubeSphere Ambassador, it is important for me to promote and support KubeSphere within the community, helping users to make the most out of this platform. I aim to convey that KubeSphere is a powerful and effective open-source solution that can make applications more flexible, scalable, and reliable. In my role as a KubeSphere Ambassador, I will actively engage with the community by sharing my own experiences and providing support to other users. I want to help them better understand and utilize KubeSphere effectively. I will participate in community events, write blog posts, and create content related to KubeSphere to encourage its adoption. Furthermore, I am eager to contribute to the continuous improvement of KubeSphere by providing feedback to the KubeSphere team and participating in the development of new features based on user needs. Encouraging the growth of the community is another important goal for me. I believe that by doing so, more users can benefit from the advantages of KubeSphere. As a KubeSphere Ambassador, my ultimate aim is to contribute to the success of the KubeSphere project and support the development of the community. I am excited to be part of this role and look forward to gaining more experience while adding value to the KubeSphere ecosystem.

### Anything you want to talk about?

Thanks for this opportunity.

**Comment by calvinyv** [comment]
Enes, welcome to join KubeSphere community

**Comment by EnesUrkmezz** [comment]
Hello, I'm very happy to have joined you.

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @calvinyv @faweizhao26

**Comment by halil-bugol** [comment]
I vote rejected

**Comment by calvinyv** [comment]
Enes, thanks for your interest in KubeSphere, and look fwd to seeing more activities in this community, KubeSphere Ambassador is the title for those people who already have made notable contributions to the KubeSphere community. I think you will definitely become the ambassador if you keep contributing in open-source way.
