### ISSUE TITLE
Application: 2023 Ambassadorship Program Application canogluonur

### ISSUE THREAD

**Issue by canogluonur** [kubesphere/community#437]
### GitHub Username

canogluonur

### Name

Onur

### Surname

Canoğlu

### Email

onurcanoglu7@gmail.com

### Social Media and Other Links About You

https://medium.com/@onurcanoglu
https://twitter.com/canoglluu
https://www.linkedin.com/in/onurcanoglu/

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [x] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [ ] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [X] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### How do you plan to contribute to the future of KubeSphere if you don't have enough requirements?

Although I may not currently meet all the requirements for KubeSphere, it won't deter me from contributing. Joining KubeSphere's Ambassadorship program demonstrates my desire to enhance the platform's value and actively contribute to its growth in collaboration with the community. I am aware of my limitations and will focus on continuous improvement.

During this period, I will actively engage in learning about KubeSphere and its ecosystem, review projects, and address community needs. I will interact with other contributors, share experiences, and actively participate in the development process to seek feedback and address any shortcomings.

My belief and passion for the future of KubeSphere will motivate me to complete any missing requirements and make valuable contributions to the project. As I progress, I will strive to become more beneficial to the project and the community by continuously improving myself.

Furthermore, I have a keen interest in CNCF products. My enthusiasm for these technologies allows me to quickly adapt and accelerate my learning process.

### Links and other resources to share with us about the requirements.

https://medium.com/@onurcanoglu
https://github.com/canogluonur/Harbor-Install-on-Docker 
https://github.com/Galipce/Hawkeye
https://github.com/canogluonur/FBI-Most-Wanted-Fugitives

### What do you think about Cloud Native? What type of experiences have you had before?

I have a very positive view of Cloud Native. In my current professional life, I actively use Cloud Native products, and I have observed many advantages of this approach, such as flexibility, scalability, and rapid deployment. Cloud Native is an approach where applications are designed and run on cloud-based infrastructure, incorporating modern techniques like microservices architecture and container technologies.

As I witness the impact of Cloud Native products, I am inspired to contribute more in this field. Therefore, my future goal is to actively contribute to products within the Cloud Native ecosystem. To achieve this, my first step will be to specialize in platforms like KubeSphere and contribute to the project's development.

By working with KubeSphere, I aim to enhance my proficiency in Cloud Native technologies and actively contribute to the advancement of the project. Collaborating with the community, seeking feedback, and striving to address any shortcomings will be a great opportunity to broaden my knowledge in the Cloud Native domain. I hope this experience will build a strong foundation for me to contribute to other Cloud Native products in the future.

### What does KubeSphere mean to you?

KubeSphere is an exciting opportunity for me and an advanced version of Kubernetes. This platform enhances application management with its user-friendly interface. By actively using Kubernetes and aiming to become a Cloud Native expert through KubeSphere, I see it as a fundamental building block for my future projects. I am eager to explore and contribute in this field.

### What are your plans after becoming an Ambassador?

After becoming an Ambassador, I aim to promote and contribute to the growth of KubeSphere. My goal is to raise awareness about KubeSphere through events, training, and blog posts. Additionally, I aspire to become a CNCF Ambassador. With knowledge about the CNCF ecosystem, I intend to emphasize the significance of the Cloud Native approach and support community expansion.

### Anything you want to talk about?

Thank you for giving me this opportunity.!

**Comment by halil-bugol** [comment]
Onur, welcome to join KubeSphere community

**Comment by canogluonur** [comment]
Hi, i'm so excited for the KubeSphere community

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @canogluonur you need to give more details for KubeSphere topics.

**Comment by halil-bugol** [comment]
Thank you @canogluonur

**Comment by halil-bugol** [comment]
I know Onur from the events we organized in Turkey. He has always been an active supporter. There isn't much content focused on KubeSphere so far, but I'm sure there will be support. I vote for him to be a KubeSphere Ambassador.

**Comment by faweizhao26** [comment]
I vote for him to be a KubeSphere Ambassador.
