### ISSUE TITLE
Application: 2023 Ambassadorship Program Application roxsross

### ISSUE THREAD

**Issue by roxsross** [kubesphere/community#438]
### GitHub Username

Roxsross

### Name

Rossana

### Surname

Suarez

### Email

roxsrossve@gmail.com

### Social Media and Other Links About You

- Linkedin https://www.linkedin.com/in/roxsross
- Twitter https://twitter.com/roxsross
- Youtube https://youtube.com/@295devops

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [X] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [X] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [ ] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [ ] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### How do you plan to contribute to the future of KubeSphere if you don't have enough requirements?

I Content Creator , about Kubesphere in community Latinoamérica,  spanish

### Links and other resources to share with us about the requirements.

https://www.linkedin.com/posts/devops-community-latam-dcl_activity-7085390414639177729-_VrS?utm_source=share&utm_medium=member_android

### What do you think about Cloud Native? What type of experiences have you had before?

I have experience about containers,  kubernets and growing with community  

### What does KubeSphere mean to you?

Automstions,  feeback and experience with developer 

### What are your plans after becoming an Ambassador?

support communities to grow

### Anything you want to talk about?

I am roxs, aws hero, docker captain and gitlab hero.

**Comment by calvinyv** [comment]
Rossana, welcome to join KubeSphere community

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @roxsross you need to give more details for KubeSphere topics before scoring.

**Comment by roxsross** [comment]
What information do you need, I just participated in two kubernetes events in communities in Spanish, do you need the link?

**Comment by halil-bugol** [comment]
Links, images, or any other information about Kubernetes events you attend. Your participation in this event and your KubeSphere advocacy.

**Comment by roxsross** [comment]
KCD Colombia ![](https://media.licdn.com/dms/image/D4D22AQH6HdXyxEwF5A/feedshare-shrink_2048_1536/0/1684025555915?e=1697068800&v=beta&t=tHIrl1-ZcwrKRuqdhDkzWgzN2UELiLov8gD7JyKV80Q)

DevOps Community Latam - DCL ![](https://media.licdn.com/dms/image/D4E22AQEehwywGPvIlg/feedshare-shrink_1280/0/1688686765837?e=1697068800&v=beta&t=_N3Um08mwrzvq6FbKO8raQy9Yx7Q-JFQTVUSLPQ3F5E)

Community Latinoamerica 

https://www.linkedin.com/in/roxsross/

**Comment by halil-bugol** [comment]
Rossana's talks for the KubeSphere community are amazing. Rossana is active in the community. I vote for her to be a KubeSphere Ambassador.

**Comment by faweizhao26** [comment]
I vote for her to be a KubeSphere Ambassador.
