### ISSUE TITLE
Application: 2023 Ambassadorship Program Application lamadome

### ISSUE THREAD

**Issue by lamadome** [kubesphere/community#439]
### GitHub Username

lamadome

### Name

Jona

### Surname

Apelbaum

### Email

jona.apelbaum@gmail.com

### Social Media and Other Links About You

- Twitter: japelbaum
- LinkedIn:  www.linkedin.com/in/jonaapelbaum

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [X] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [ ] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [X] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### How do you plan to contribute to the future of KubeSphere if you don't have enough requirements?

- I would like to contribute to the project by improving the Istio implementation and integrate with Gloo Platform eventually
-  I would like to organize live webinars together with Kubesphere and write some blogs on it
- Participate at speak at some of the kubesphere events. 

### Links and other resources to share with us about the requirements.

- https://www.linkedin.com/posts/jonaapelbaum_hot-of-the-press-the-schedule-has-been-activity-7072260088303902720-GSP7?utm_source=share&utm_medium=member_desktop
- https://www.youtube.com/watch?v=YmH-9BcH1CY&amp;index=106&amp;ab_channel=NDCConferences
- https://www.linkedin.com/posts/jonaapelbaum_api-ecosystems-connecting-physical-and-activity-7067593635076145153-x2jW?utm_source=share&utm_medium=member_desktop
- https://www.linkedin.com/posts/jonaapelbaum_quels-sont-les-nouveaux-enjeux-de-lexposition-activity-7067554447802941440-qRqM?utm_source=share&utm_medium=member_desktop

And more, I will be publishing 3 blogs later this year talking about GitOps as well. 

### What do you think about Cloud Native? What type of experiences have you had before?

Cloud Native, in my opinion, is simply the future of software. It's about building and running apps that can really take advantage of what the cloud has to offer. Cloud Native is a game-changer. It's all about leveraging the cloud to build and run better apps.

I've worked a lot with microservices, Docker, and Kubernetes - it's like neatly packing up an orchestra's worth of musicians and having a superb conductor to guide them.

One of my favorite tools in the Cloud Native toolbox is the service mesh. I've worked extensively with it and let me tell you, it's a lifesaver when you're dealing with a ton of services that need to talk to each other. It's like a top-notch traffic controller for your apps.

So, in a nutshell, Cloud Native is a smart way of building apps, and my experiences, especially with service mesh, make me excited about becoming a KubeSphere Ambassador.

### What does KubeSphere mean to you?

For me, KubeSphere takes all the cool, yet complex stuff from Kubernetes and makes it simple and accessible. It's like having a personal assistent for 'Kubernetes' :)

KubeSphere is also about making that jump from the old-school way of doing IT to embracing the cloud. It's like swapping your old flip phone for a smartphone.

### What are your plans after becoming an Ambassador?

Once I become a KubeSphere Ambassador, my main goal is to help spread the word about KubeSphere within my own professional network. I'll aim to have casual chats with friends and colleagues, sharing my experiences and the benefits of using KubeSphere.

I also plan on participating in online forums and communities during my free time, where I can share my knowledge, answer questions, and help troubleshoot problems. This is a great way to support the community without needing a huge time commitment.

Finally, I want to stay updated with the latest advancements in KubeSphere and the wider Cloud Native world. I'll take advantage of webinars and other online resources that fit into my schedule. In this way, I can keep learning and improving my skills at my own pace.

In essence, becoming a KubeSphere Ambassador, for me, is about leveraging the time I have to support others, grow personally, and promote this platform that I believe in.

**Comment by calvinyv** [comment]
Jona, welcome to join KubeSphere community.

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @calvinyv @faweizhao26

**Comment by calvinyv** [comment]
Jona is very active in KubeSphere online and offline events, and shows great passion in opensource, I vote for him to be the KubeSphere Ambassador.

**Comment by faweizhao26** [comment]
I vote for him to be the KubeSphere Ambassador. I look forward to seeing more of his blogs about KubeSphere!

**Comment by lamadome** [comment]
Thank you everyone! Looking forward for further collaboration on blogs and events! Cheers!!!
