### ISSUE TITLE
Application: 2023 Ambassadorship Program Application nilofe

### ISSUE THREAD

**Issue by nilofe** [kubesphere/community#440]
### GitHub Username

@nilofe

### Name

Nilo

### Surname

Yucra Gavilan

### Email

nyucragavilan@gmail.com

### Social Media and Other Links About You

[Linkedin](https://www.linkedin.com/in/nilofe/)  -  [Blog](https://realstw.com/)

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [ ] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [X] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### How do you plan to contribute to the future of KubeSphere if you don't have enough requirements?

- I have in mind, to organize a kubesphere event in my local language (Spanish).
- contribute building a spanish speaking block in the kubesphere documentation if possible.
- write blogs and make tutorials about kubesphere, about its architecture, networking, storage, others. and its integrations in production with cloud native products.

### Links and other resources to share with us about the requirements.

I talked about kubesphere earlier this year at a "Devops today Lima" conference, but I only have pictures.

### What do you think about Cloud Native? What type of experiences have you had before?

- cloud native gives approaches, methodologies and uses powerful tools for different customizable and scalable solutions in different environments, I like it because there is no absolute approach or method for all industries, there is always someone who is trying to apply a new one or improving, discovering or doing something extraordinary from the garage of his house.
- The experience with cloud native has allowed me to develop and build many things in the companies I've been in, I've always stood out for looking for new solutions and learning them,  
I have been able to build more scalable environments, change the approach to use the tools and methodologies of each team where I have been, it has certainly helped me to develop myself in a much broader way, and above all always think that I will not have the reason or solution to all problems, that excites me.

### What does KubeSphere mean to you?

For me it is a platform with a lot of potential and with a very viable market share in time, it solves many problems of hybrid systems, to be honest I had not heard of kubepshere, until earlier this year, I tried it and I liked it.

### What are your plans after becoming an Ambassador?

- make kubesphere tutorials on youtube about its use and how it integrates with cloud native tools.
- I will organize conferences 1 or 2 times a year, I would also like to create an official kubesphere community in my country.
- create blogs about the use of kubesphere.
- give talks and workshops about Kubesphere and other things if I have enough time.

### Anything you want to talk about?

well, I do not meet some requirements but that is not a limitation to talk about kubesfera, I will write blogs, and talk about this tool and I will try next year if I am not elected, thanks for everything greetings.

**Comment by calvinyv** [comment]
Nilo, welcome to join KubeSphere community

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @nilofe you need to give more details for KubeSphere topics before scoring. Example: You can share photos Devops today Lima event.

**Comment by halil-bugol** [comment]
ping @nilofe

**Comment by faweizhao26** [comment]
I vote for him to be a KubeSphere Ambassador.
