### ISSUE TITLE
Application: 2023 Ambassadorship Program Application iremonder

### ISSUE THREAD

**Issue by iremonder** [kubesphere/community#441]
### GitHub Username

@iremonder

### Name

İREMNUR

### Surname

ÖNDER

### Email

onderirem18@gmail.com

### Social Media and Other Links About You

https://www.linkedin.com/in/irem-%C3%B6nder-21ab5924b/

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [X] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [ ] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### How do you plan to contribute to the future of KubeSphere if you don't have enough requirements?

By looking at the documentation and guides related to Kubesphere, I can identify missing or need to be updated documents and contribute to their development. I can contribute at an international level by sharing about documentation translations on social media.

I can also continue my support with presentations and events where I can share information about kubesphere.

### Links and other resources to share with us about the requirements.

https://www.kubesphere.io/news/explore-cncf-kcd-turkey-with-kubesphere-turkey/

https://www.linkedin.com/in/irem-%C3%B6nder-21ab5924b/

### What do you think about Cloud Native? What type of experiences have you had before?

Cloud native approach, in line with the principles of continuous integration and continuous distribution (CI/CD), allows application updates to be released quickly and securely.

cloud native is an approach developed to respond to today's rapidly changing software development needs. However, because every project and organization is different, it is important to determine the best way to implement cloud native.

### What does KubeSphere mean to you?

As KubeSphere is an open source project, it is developed and contributed by the community. It also allows organizations to manage applications in accordance with cloud native principles by using KubeSphere in their infrastructure.

  KubeSphere is a platform that helps more effectively manage applications running on Kubernetes and facilitates the implementation of modern software development approaches. It is the easiest, clear and understandable path tracking tool for us.

### What are your plans after becoming an Ambassador?

I would like to further promote and develop as part of the community by contributing to the kubesphere project. Further development of KubeSphere can be achieved by reaching large audiences and events.

It can contribute to the international dissemination of the project by translating the KubeSphere documentation or user interface into different languages.

### Anything you want to talk about?

No there's not.

**Comment by halil-bugol** [comment]
Irem, welcome to join KubeSphere community

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @calvinyv @faweizhao26

**Comment by faweizhao26** [comment]
I vote for her to be a KubeSphere Ambassador. Welcome to join KubeSphere community.

**Comment by calvinyv** [comment]
@iremonder welcome and thanks for the help on the documentation.
