### ISSUE TITLE
REQUEST: New membership for KubeSphere User Group ShangHai

### ISSUE THREAD

**Issue by yongxingMa** [kubesphere/community#442]
Hello, I am a development engineer, the main direction is cloud native and edge computing. Often use Kubesphere products and participate in Kubesphere community activities, recently participated in the Kubesphere Shanghai meet up support, I hope to join the KubeSphere User Group ShangHai, thank you!

**Comment by faweizhao26** [comment]
Support! Welcome aboard.

**Comment by webup** [comment]
Support, welcome @yongxingMa ~

**Comment by faweizhao26** [comment]
I will add your profile to the page of [KubeSphere website](https://www.kubesphere.io/zh/user-group/shanghai/).
Now I close this issue.
