### ISSUE TITLE
Application: 2023 Ambassadorship Program Application HaruEr

### ISSUE THREAD

**Issue by HaruEr** [kubesphere/community#445]
### GitHub Username

HaruEr

### Name

Harun Eren

### Surname

SAT

### Email

haruneren.sat@hotmail.com

### Social Media and Other Links About You

LinkedIn: https://www.linkedin.com/in/harunerensat/ 

Medium: https://medium.com/@haruneren.sat 

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [X] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [X] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### Links and other resources to share with us about the requirements.

- https://www.linkedin.com/posts/harunerensat_community-cloud-kubernetes-activity-7075678593032294400-cRCz?utm_source=share&utm_medium=member_desktop 

 

- https://www.linkedin.com/posts/harunerensat_explore-cncf-kcd-turkey-with-kubesphere-turkey-activity-7084061588608925697-3_QP?utm_source=share&utm_medium=member_desktop 

 

- https://www.linkedin.com/posts/harunerensat_logstack-activity-7089980313233166336-JQN5?utm_source=share&utm_medium=member_desktop 

 

- https://www.linkedin.com/posts/harunerensat_open-source-enterprise-kubernetes-platform-activity-7062435077284069376-eLjl?utm_source=share&utm_medium=member_desktop 

 

- https://medium.com/@haruneren.sat/logstack-241288f660a5 

 

- https://www.linkedin.com/feed/update/urn:li:activity:6984180224150122496?utm_source=share&utm_medium=member_desktop 

 

- https://www.linkedin.com/feed/update/urn:li:activity:7064344900254769152?utm_source=share&utm_medium=member_desktop 

 

- https://www.linkedin.com/posts/harunerensat_cloud-huawei-kubesphere-activity-6984254162402185216-12Ln?utm_source=share&utm_medium=member_desktop 

 

- https://www.linkedin.com/posts/harunerensat_kubesphere-t%C3%BCrkiye-forumu-a%C3%A7%C4%B1ld%C4%B1-kubesphere-activity-7059530148949241856-FrBz?utm_source=share&utm_medium=member_desktop 

### What do you think about Cloud Native? What type of experiences have you had before?

Cloud Native provides several advantages and conveniences to people as an approach. For example:

Fast and Agile Development: Cloud Native applications are designed as microservices, allowing different teams to work independently. This enables a quick and flexible development process, leading to faster releases of new features and updates.

High Scalability: Cloud Native architectures allow easy scalability to increase or decrease workload. This helps businesses respond better to sudden traffic spikes or high demands, providing improved services.

Enhanced Reliability and Resilience: Cloud Native applications can be more resilient as microservices can operate independently. Even if one service fails, others can continue to function, making the system more reliable.

Reusability: With container technologies, applications and services can be easily portable and reusable across various environments, saving time and resources.

Reduced Operational Burden: Automated deployment, scaling, and management processes in Cloud Native applications reduce operational burden and lower operational costs.

Rapid Feedback and Improvement: CI/CD processes enable quick testing and deployment of code changes, facilitating rapid identification and rectification of errors.

Less Dependency: Containers provide isolated environments where applications and services can run independently, reducing dependencies between technology stacks and infrastructures.

Easy Monitoring and Analysis: Cloud Native applications can integrate with centralized logging and monitoring systems, simplifying performance, security, and error tracking and analysis.

These conveniences and advantages bring great benefits to people.

I participated in Kubernetes events with Cloud Native Turkey. Apart from that, I work voluntarily with CNCF Glossary.

### What does KubeSphere mean to you?

KubeSphere is my currently stands as my home of growth and learning. I see it as a structure that allows me to step into the world of Kubernetes, reduces the workload with its user-friendly interface, and makes it easier to dream.

### What are your plans after becoming an Ambassador?

If elected as Ambassador, I will strive for the development and recognition of KubeSphere. By taking an active role in Kubernetes communities, I will actively explain the usefulness and user-friendliness of KubeSphere. I will conduct active promotions by organizing KubeSphere workshops. Apart from these, most importantly, I will try to create a community that is strong and beneficial for each other's development.

### Anything you want to talk about?

I look forward to further success with KubeSphere.

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated.

**Comment by halil-bugol** [comment]
Harun is a member of the communty team we created in Turkey. I am sure that there will be support and I vote for him to be a KubeSphere Ambassador.

**Comment by faweizhao26** [comment]
I vote for him to be a KubeSphere Ambassador.

**Comment by calvinyv** [comment]
+1
@HaruEr  enjoy KubeSphere community ~

**Comment by HaruEr** [comment]
It is exciting to take steps towards more tremendous success together. Thank you all.
