### ISSUE TITLE
REQUEST: Apply to join the User Group in Hangzhou

### ISSUE THREAD

**Issue by zhuyaguang** [kubesphere/community#447]
### GitHub ID

zhuyaguang

### City Name

Hangzhou

### Prerequisites for User Group

- [X] Currently there are only five cities (Shanghai, Hangzhou, Chengdu, Guangzhou, Shenzhen) with user groups, so you can only apply for these five cities.

### Contact information

wechat:love1368

### Reason to join a User Group

参与社区建设，接触业界大佬，提高技术水平

### Requirements

- [X] Recently active in the KubeSphere community, with a relatively high interest and plenty of energy in community development and organizing events.
- [X] Have some communication and organizational skills.

### Plans after joining a user group

围绕 基于  kubesphere 的云原生底座，进行 DevOps 、微服务治理、大数据、AI 方面的实践。

**Comment by yinmin2020** [comment]
support

**Comment by faweizhao26** [comment]
Support, welcome!

**Comment by faweizhao26** [comment]
I have add your information to the page of webstie.
Link: https://www.kubesphere.io/zh/user-group/hangzhou/
So I close this issue now.
