### ISSUE TITLE
Application: 2023 Ambassadorship Program Application emirhandogandemir

### ISSUE THREAD

**Issue by emirhandogandemir** [kubesphere/community#448]
### GitHub Username

emirhandogandemir

### Name

Emirhan

### Surname

Doğandemir

### Email

emirhandgndmr51@gmail.com

### Social Media and Other Links About You

linkedin.com/in/emirhandogandemir
medium.com/@emirhandogandemir

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [X] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [ ] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [X] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### Links and other resources to share with us about the requirements.

https://medium.com/@emirhandogandemir/ansible-nedir-neden-kullan%C4%B1l%C4%B1r-konseptleri-nelerdir-58afdc25d80f
https://www.youtube.com/watch?v=RiLJLBKUj6I
https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/b02980c8-56cd-4edd-aaf1-022047bd6849-emirhan-doandemir-e95ed7eb-4a66-4708-a07f-772ab312fe28-certificate.pdf
https://www.credly.com/badges/8dad12d8-7802-49d6-ac5d-6d0d17bc7790/linked_in_profile
https://github.com/emirhandogandemir/jib-maven-pluginAndHelm-Twistlock
https://github.com/emirhandogandemir/java-DevOps-Project

### What do you think about Cloud Native? What type of experiences have you had before?

My perspective on Cloud Native is deeply positive. Within my current professional sphere, I am actively engaged with Cloud Native products, and the manifold benefits of this paradigm have become evident to me. The attributes of flexibility, scalability, and rapid deployment have stood out prominently. Cloud Native, as an approach, revolves around crafting and operating applications on cloud-based infrastructure, seamlessly integrating modern methodologies like microservices architecture and container technologies.

As I bear witness to the transformative potential of Cloud Native products, a profound desire to make meaningful contributions within this domain takes root within me. Consequently, I've set my sights on an ambitious future goal: to play an active role in shaping products within the expansive Cloud Native ecosystem. My inaugural stride toward this aspiration entails cultivating specialization in platforms like KubeSphere and actively participating in the evolution of its project landscape.

### What does KubeSphere mean to you?

KubeSphere presents a captivating opportunity for me, representing an evolved iteration of Kubernetes. Within this platform lies a potent catalyst that elevates application management, thanks to its remarkably intuitive user interface. My engagement with Kubernetes has been enthusiastic, and my aspirations revolve around attaining mastery as a Cloud Native specialist, with KubeSphere as my guiding companion. It stands as an indispensable cornerstone for my upcoming ventures, poised to infuse a distinctive essence into my future projects. The anticipation to delve into this realm, actively contribute, and chart new frontiers is a driving force that fuels my journey.

### What are your plans after becoming an Ambassador?

As I transition into my role as an Ambassador, my primary objective revolves around strengthening the growth of KubeSphere, an innovative Kubernetes platform. I am dedicated to contributing to KubeSphere's evolution by raising awareness through a series of well-orchestrated events, comprehensive training sessions, and thought-provoking blog posts. My ultimate goal also involves obtaining the esteemed position of a CNCF Ambassador.

With an intricate understanding of the CNCF ecosystem, I am committed to emphasizing the importance of adopting the Cloud Native approach. Simultaneously, I will actively participate in expanding the community, while also focusing on the niche field of specialized security.

### Anything you want to talk about?

Thank you for giving me this opportunity.!

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @emirhandogandemir  you need to give more details for KubeSphere topics before scoring.

**Comment by halil-bugol** [comment]
ping @emirhandogandemir

**Comment by emirhandogandemir** [comment]
Of course, I would like to provide more detailed information about KubeSphere topics and its content.

KubeSphere is a platform that serves as a distributed operating system for cloud-native application management, utilizing Kubernetes as its core. It offers a plug-and-play architecture, enabling seamless integration of third-party applications into its ecosystem. As a lightweight platform, KubeSphere is more adaptable to various cloud ecosystems since it does not alter Kubernetes itself in any way. In other words, KubeSphere can be deployed on any existing version-compatible Kubernetes cluster, across various infrastructures including virtual machines, bare metal, on-premises, public cloud, and hybrid cloud environments.

Here are some of the features of KubeSphere:

- CI/CD Pipeline
- Source-to-Image
- Istio-based Service Mesh
- Multi-tenant Management
- Observability
- Alerting, Events, Auditing, and Notifications

And here are the advantages it provides:
- Vision
- Powerful observability
- Automated DevOps
- Fine-grained access control
- Out-of-box microservices governance
- Vibrant open source community

@halil-bugol

**Comment by halil-bugol** [comment]
I know Emirhan from Turkey. Very active in the CNCF community. I vote for him to be Ambassador.
