### ISSUE TITLE
Application: 2023 Ambassadorship Program Application k8sk-kevin

### ISSUE THREAD

**Issue by k8sk-kevin** [kubesphere/community#451]
### GitHub Username

@k8sk-kevin

### Name

Kevin

### Surname

Xu

### Email

13570805860@163.com

### Social Media and Other Links About You

Wechat: 13570805860

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [X] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [ ] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### Links and other resources to share with us about the requirements.

https://kubesphere.io/
https://github.com/kubesphere/kubesphere

### What do you think about Cloud Native? What type of experiences have you had before?

Cloud Native is an approach to building and running applications that takes full advantage of cloud computing models and principles. It involves designing applications specifically for deployment in cloud environments and leveraging the benefits of scalability, flexibility, and resilience that the cloud provides.

Orchestration platforms like KubeSphere are often used to manage and automate the deployment, scaling, and monitoring of Cloud Native applications. KubeSphere provides features for container orchestration, service discovery, load balancing, and self-healing, among others.

### What does KubeSphere mean to you?

Productivity：
Getting more work done with fewer people is a common goal for organizations seeking to improve efficiency and productivity。

### What are your plans after becoming an Ambassador?

If elected as Ambassador,
First, Interactive community members for more frequently activities in online or offline;
secondary,  Feedback and insights, Collect issue and suggestions to KubeSphere Team;
In addition, I will cooperate with KS community   organizing ShenZhen KubeSphere workshops.

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @k8sk-kevin  you need to give more details for KubeSphere topics before scoring.

**Comment by faweizhao26** [comment]
> 🟢 The application is valid. It will be evaluated. @k8sk-kevin you need to give more details for KubeSphere topics before scoring.

https://www.kubesphere.io/zh/case/bobinfo/
https://www.kubesphere.io/zh/live/shenzhen0408-api/

**Comment by faweizhao26** [comment]
Kevin is the leader of KubeSphere User Group in Shenzhen. He was one of the main organisers of the Shenzhen meetup in April this year. In addition he has shared best practices many times in the community. I vote for him to be the KubeSphere Ambassador.

**Comment by halil-bugol** [comment]
I vote for him to be a KubeSphere Ambassador
