### ISSUE TITLE
Application: 2023 Ambassadorship Program Application webup

### ISSUE THREAD

**Issue by webup** [kubesphere/community#452]
### GitHub Username

webup

### Name

Haili

### Surname

Zhang

### Email

haili.zhang@outlook.com

### Social Media and Other Links About You

- Twitter: [@zhanghaili0610](https://twitter.com/zhanghaili0610)
- BiliBilli: [沧海九粟](https://space.bilibili.com/28357052)
- Yuque: [serviceup](https://www.yuque.com/serviceup)

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [ ] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [X] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [ ] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### Links and other resources to share with us about the requirements.

- KubeSphere Meetup: [AI + Serverless Meetup 上海站（8.5）精彩回顾（视频回放 + PPT）](https://mp.weixin.qq.com/s/KJmoioPFH7FtRUK47JQCxQ)
- OpenFunction OSPP: [OSPP 2023](https://summer-ospp.ac.cn/org/prodetail/236690197?lang=en&list=pro)

### What do you think about Cloud Native? What type of experiences have you had before?

Please refer to my sharing in [KubeSphere Talk 第三期已上线——嘉宾：张海立](https://mp.weixin.qq.com/s/22A9MQruk0tjyZOSXYFXNA)

### What does KubeSphere mean to you?

A good product, a reliable partner.

### What are your plans after becoming an Ambassador?

- Continue to help the community to promote KubeSphere in the local market
- Continue my contribution in OpenFunction project
- Continue to broadcast KubeSphere message via my personal channels in social media

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @calvinyv @faweizhao26

**Comment by faweizhao26** [comment]
Haili is the leader of KubeSphere User Group in Shanghai. He is very active in KubeSphere Community. I vote for him to be the KubeSphere Ambassador.

**Comment by calvinyv** [comment]
+1
Welcome

**Comment by halil-bugol** [comment]
I vote for him to be a KubeSphere Ambassador
