### ISSUE TITLE
Application: 2023 Ambassadorship Program Application kissycn

### ISSUE THREAD

**Issue by kissycn** [kubesphere/community#455]
### GitHub Username

kissycn

### Name

zhengjun

### Surname

zhou

### Email

kissycn@gmail.com

### Social Media and Other Links About You

- Twitter
@kissycn

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [ ] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [ ] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### How do you plan to contribute to the future of KubeSphere if you don't have enough requirements?

1. Organize online or offline Meetup and technology sharing
2. Follow up the latest developments in the community and product updates in a timely manner to find problems and submit improvements
3. Integrate our existing product functions through the plug-in mechanism of KS4.0

### Links and other resources to share with us about the requirements.

https://kubesphere.io/
https://github.com/kubesphere/kubesphere

### What do you think about Cloud Native? What type of experiences have you had before?

1. Cloud native is a resource orchestration system decoupled from infrastructure, which can run in any data center environment.
2. Cloud native shields the complexity of the underlying infrastructure, allowing us to focus on the construction and operation of the last application.
3. Cloud native is an inclusive technology, which enables more small and medium-sized enterprises to achieve digitalization more conveniently.

I have used cloud foundry to build an enterprise PAAS platform, and I have also witnessed and experienced the convenience brought by Docker, and finally chose cloud-native related industries

### What does KubeSphere mean to you?

1. An out-of-the-box enterprise-level cloud-native governance platform
2. A cloud-native platform that integrates rich plug-in applications
3. A simple and efficient application governance platform that shields the complexity of the underlying technology
4. A useful, beautiful appearance and simple management platform

### What are your plans after becoming an Ambassador?

1. Organize online or offline Meetup and technology sharing
2. Follow up the latest developments in the community and product updates in a timely manner to find problems and submit improvements
3. Integrate our existing product functions through the plug-in mechanism of KS4.0

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated.

**Comment by faweizhao26** [comment]
zhengjun is the leader of KubeSphere User Group in Chengdu. He was one of the main organisers of several KubeSphere meetups in Chengdu. I vote for him to be the KubeSphere Ambassador.
