### ISSUE TITLE
Application: 2023 Ambassadorship Program Application Jacklalala

### ISSUE THREAD

**Issue by Jacklalala** [kubesphere/community#457]
### GitHub Username

Jacklalala

### Name

郑建林

### Surname

郑

### Email

xyzszjl@126.com

### Social Media and Other Links About You

个人介绍及kubesphere开源布道分享：https://mp.weixin.qq.com/s/ajCFH3TbkOACXUxrC32gxA

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [X] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [ ] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### Links and other resources to share with us about the requirements.

kuebsphere实践文章分享：https://mp.weixin.qq.com/s/rNbjf0L3H3mI7D90mxDbFw
                                     https://blog.csdn.net/xinsuiqingfeng/article/details/132594875
kubesphere线下活动组织：https://mp.weixin.qq.com/s/onjq8U4G6yswxNBbPRKnpw?poc_token=HEKt8GSj9EdDJ6kiCFfOHZhNPfr9lXxxhu7HaBHa
kubesphere主播分享心得：https://mp.weixin.qq.com/s/ajCFH3TbkOACXUxrC32gxA

### What do you think about Cloud Native? What type of experiences have you had before?

个人从2018年开始接触使用k8s和docker等云原生技术来搭建服务集群，并推进cicd持续集成持续发布的敏捷研发流程，体验到云原生给基础设施资源管理利用和开发效率的极大提升，后续不断尝试将服务流量网关apisix和服务网格istio等新生云原生技术应用到项目里，并由开始自己开发的容器管理逐步切换到使用开源的容器管理平台openshift，rancher再到去年使用kubesphere容器管理平台并一直使用至今，在开发，测试生产环境都深度依赖使用，后续计划更深入了解开发能够自主开发插件应用到项目中满足公司项目的基础平台需求，完全拥抱云原生。

### What does KubeSphere mean to you?

自从使用kubesphere后我们团队完全不需要投入大量精力去开发容器管理平台，也不用为使用和管理云原生各个组件而头疼，kubesphere提供了从基础资源管理到中间间，devops，监控等一站式方案，极大节省了人力投入，并且高效可维护基础容器服务平台，可以很放心将项目中的k8s集群和服务交给kubepshere平台来管理。

### What are your plans after becoming an Ambassador?

1. 深入理解kubesphere云原生技术和开源理念，在项目实践过程中解决实际问题并总结经验分享。
2. 组织和协助kubesphere社区开源布道活动开展，推进社区走进更多的企业和开发使用者，同时自己也跟随社区和志同道合朋友不断深入kubesphere生态云原生技术。
3. 自己成为kubesphere的深度开发应用者，拥抱云原生，希望能成为行业技术引领者和开拓者。

### Anything you want to talk about?

kubesphere生态越来越健全，围绕云原生技术不断深耕，作为其中使用开发和推进者也需要不断前进。

**Comment by halil-bugol** [comment]
🟢 The application is valid. It will be evaluated. @calvinyv @faweizhao26

**Comment by faweizhao26** [comment]
Jacklalala is one member of KubeSphere User Group in Shenzhen. He is acitve in KubeSphere Community.  I vote for him to be the KubeSphere Ambassador.

**Comment by halil-bugol** [comment]
We look forward to more events in Shenzhen. I vote for him to be the KubeSphere Ambassador.
