### ISSUE TITLE
Application: 2023 Ambassadorship Program Application akin-kaya

### ISSUE THREAD

**Issue by akin-kaya** [kubesphere/community#458]
### GitHub Username

akin-kaya

### Name

Akın

### Surname

Kaya

### Email

akin.kaya@gmail.com

### Social Media and Other Links About You

https://www.linkedin.com/in/akin-kaya-14742820/

### Basic Requirements

- [X] Must be 18 years of age or older.
- [X] You need to have active knowledge of Cloud Native architectures.
- [X] To have technological or other knowledge that will contribute to the future of KubeSphere.

### Requirements

- [ ] To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
- [ ] Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
- [X] Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
- [ ] Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.

### Links and other resources to share with us about the requirements.

https://www.medipol.edu.tr/haberler/kubernetes-community-days-turkiyede-ilk-kez-medipolde-duzenlendi

### What do you think about Cloud Native? What type of experiences have you had before?

The Cloud Native Computing Foundation (CNCF) is an open source organization that helps organizations start their cloud-based journey. Founded in 2015, CNCF supports the open source community in developing critical cloud-based components, including Kubernetes. At the same time, we are creating an open source version of an application we developed to be a part of this organization.

### What does KubeSphere mean to you?

Kubernetes is one of the biggest players in the development of technologies.

### What are your plans after becoming an Ambassador?

I would like to support universities to be included in the courses given in engineering programs.

**Comment by halil-bugol** [comment]
🔴 The application is not valid. It cannot be evaluated. @akin-kaya You must meet a minimum of two requirements.
