### ISSUE TITLE
REQUEST: Apply to join the User Group in hangzhou

### ISSUE THREAD

**Issue by zhaojizhuang** [kubesphere/community#464]
### GitHub ID

zhaojizhuang

### City Name

hangzhou

### Prerequisites for User Group

- [X] Currently there are only five cities (Shanghai, Hangzhou, Chengdu, Guangzhou, Shenzhen) with user groups, so you can only apply for these five cities.

### Contact information

wechat: zjz_chumper

### Reason to join a User Group

云原生社区技术交流，相关技术分享

### Requirements

- [X] Recently active in the KubeSphere community, with a relatively high interest and plenty of energy in community development and organizing events.
- [X] Have some communication and organizational skills.

### Plans after joining a user group

不定期分享云原生、Serverless、容器运行时相关技术

**Comment by faweizhao26** [comment]
Support, welcome!

**Comment by yinmin2020** [comment]
Support, welcome!

**Comment by faweizhao26** [comment]
I have add your information to the page of webstie.
Link: https://www.kubesphere.io/zh/user-group/hangzhou/
So I close this issue now.
