### ISSUE TITLE
Apply to join the User Group in hangzhou

### ISSUE THREAD

**Issue by zhangduanya** [kubesphere/community#465]
### GitHub ID

zhangduanya

### City Name

Shanghai

### Prerequisites for User Group

- [X] Currently there are only five cities (Shanghai, Hangzhou, Chengdu, Guangzhou, Shenzhen) with user groups, so you can only apply for these five cities.

### Contact information

zhdyaa

### Reason to join a User Group

热衷于kubernetes的发展，希望通过加入贵圈，持续跟进最新的技术动态、研究趋势和最佳实践！

### Requirements

- [X] Recently active in the KubeSphere community, with a relatively high interest and plenty of energy in community development and organizing events.
- [X] Have some communication and organizational skills.

### Plans after joining a user group

结合KubeSphere的特性，如何优化微服务架构设计、服务注册与发现、熔断限流、链路追踪等问题。

**Comment by faweizhao26** [comment]
Support, welcome!

**Comment by yinmin2020** [comment]
Support, welcome!

**Comment by faweizhao26** [comment]
I have add your information to the page of webstie.
Link: https://www.kubesphere.io/zh/user-group/hangzhou/
So I close this issue now.
