### ISSUE TITLE
REQUEST: Apply to join the User Group in [Hangzhou] 

### ISSUE THREAD

**Issue by ssslkj123** [kubesphere/community#466]
### GitHub ID

ssslkj123

### City Name

Hangzhou 

### Prerequisites for User Group

- [X] Currently there are only five cities (Shanghai, Hangzhou, Chengdu, Guangzhou, Shenzhen) with user groups, so you can only apply for these five cities.

### Contact information

wechat: Fedora_lee

### Reason to join a User Group

- Participate in community building.
- Write and modify Kubesphere project’s best practice articles, meet open source community contributors, and learn cloud-native technology together.

### Requirements

- [X] Recently active in the KubeSphere community, with a relatively high interest and plenty of energy in community development and organizing events.
- [X] Have some communication and organizational skills.

### Plans after joining a user group

Based on the Kubesphere open-source distribution as the foundation, contribute articles related to best practices in DevOps, application Observability, and Microservices governance.

**Comment by yinmin2020** [comment]
Support, welcome!

**Comment by faweizhao26** [comment]
Support, welcome!

**Comment by faweizhao26** [comment]
I have add your information to the page of webstie.
Link: https://www.kubesphere.io/zh/user-group/hangzhou/
So I close this issue now.
