### ISSUE TITLE
Build controller-manager image error

### ISSUE THREAD

**Issue by xuhua912** [kubesphere/community#57]
### The environment
centos 7.7
kubesphere 2.1.1
docker 19.03.8

###  controller-manager Dockerfile
`FROM golang:1.12 as controller-manager-builder

COPY / /go/src/kubesphere.io/kubesphere
WORKDIR /go/src/kubesphere.io/kubesphere

RUN CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 GOFLAGS=-mod=vendor go build --ldflags "-extldflags -static" -o controller-manager ./cmd/controller-manager/

FROM alpine:3.7
_RUN echo -e "https://mirrors.ustc.edu.cn/alpine/latest-stable/main\nhttps://mirrors.ustc.edu.cn/alpine/latest-stable/community" > /etc/apk/repositories && \_
apk add --update ca-certificates && update-ca-certificates
COPY --from=controller-manager-builder /go/src/kubesphere.io/kubesphere/controller-manager /usr/local/bin/
CMD controller-manager`

### Shell 
`docker build -f build/ks-controller-manager/Dockerfile -t harbor.xx.net.cn:8443/ks-controller-manager:2.1.1 .`

### Output
```
Sending build context to Docker daemon  141.6MB
Step 1/8 : FROM golang:1.12 as controller-manager-builder
 ---> ffcaee6f7d8b
Step 2/8 : COPY / /go/src/kubesphere.io/kubesphere
 ---> ce4ec5aec998
Step 3/8 : WORKDIR /go/src/kubesphere.io/kubesphere
 ---> Running in 653b62e681e8
Removing intermediate container 653b62e681e8
 ---> fd87a5dbab82
Step 4/8 : RUN CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 GOFLAGS=-mod=vendor go build --ldflags "-extldflags -static" -o controller-manager ./cmd/controller-manager/
 ---> Running in a9dda2856eed
Removing intermediate container a9dda2856eed
 ---> 88b836d3e8e7
Step 5/8 : FROM alpine:3.7
 ---> 6d1ef012b567
Step 6/8 : RUN echo -e "https://mirrors.ustc.edu.cn/alpine/latest-stable/main\nhttps://mirrors.ustc.edu.cn/alpine/latest-stable/community" > /etc/apk/repositories && apk add --update ca-certificates && update-ca-certificates
 ---> Running in 4e038f46cf66
fetch https://mirrors.ustc.edu.cn/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.ustc.edu.cn/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libcrypto1.1 (1.1.1g-r0)
**ERROR: libcrypto1.1-1.1.1g-r0: trying to overwrite etc/ssl/openssl.cnf owned by libressl2.6-libcrypto-2.6.5-r0.**
(2/2) Installing ca-certificates (20191127-r1)
Executing busybox-1.27.2-r11.trigger
Executing ca-certificates-20191127-r1.trigger
1 error; 8 MiB in 15 packages
**The command '/bin/sh -c echo -e "https://mirrors.ustc.edu.cn/alpine/latest-stable/main\nhttps://mirrors.ustc.edu.cn/alpine/latest-stable/community" > /etc/apk/repositories && apk add --update ca-certificates && update-ca-certificates' returned a non-zero code: 1**
```

**Comment by xuhua912** [comment]
`FROM golang:1.12 as controller-manager-builder

COPY / /go/src/kubesphere.io/kubesphere
WORKDIR /go/src/kubesphere.io/kubesphere

RUN CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 GOFLAGS=-mod=vendor go build --ldflags "-extldflags -static" -o controller-manager ./cmd/controller-manager/

FROM alpine:3.7
RUN echo -e "https://mirrors.ustc.edu.cn/alpine/latest-stable/main\nhttps://mirrors.ustc.edu.cn/alpine/latest-stable/community" > /etc/apk/repositories && \
apk add --update ca-certificates && update-ca-certificates
COPY --from=controller-manager-builder /go/src/kubesphere.io/kubesphere/controller-manager /usr/local/bin/
CMD controller-manager`


`# docker build -f build/ks-controller-manager/Dockerfile -t harbor.belle.net.cn:8443/ks-controller-manager:2.1.1 .
Sending build context to Docker daemon  141.6MB
Step 1/8 : FROM golang:1.12 as controller-manager-builder
 ---> ffcaee6f7d8b
Step 2/8 : COPY / /go/src/kubesphere.io/kubesphere
 ---> ce4ec5aec998
Step 3/8 : WORKDIR /go/src/kubesphere.io/kubesphere
 ---> Running in 653b62e681e8
Removing intermediate container 653b62e681e8
 ---> fd87a5dbab82
Step 4/8 : RUN CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 GOFLAGS=-mod=vendor go build --ldflags "-extldflags -static" -o controller-manager ./cmd/controller-manager/
 ---> Running in a9dda2856eed
Removing intermediate container a9dda2856eed
 ---> 88b836d3e8e7
Step 5/8 : FROM alpine:3.7
 ---> 6d1ef012b567
Step 6/8 : RUN echo -e "https://mirrors.ustc.edu.cn/alpine/latest-stable/main\nhttps://mirrors.ustc.edu.cn/alpine/latest-stable/community" > /etc/apk/repositories && apk add --update ca-certificates && update-ca-certificates
 ---> Running in 4e038f46cf66
fetch https://mirrors.ustc.edu.cn/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.ustc.edu.cn/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libcrypto1.1 (1.1.1g-r0)
ERROR: libcrypto1.1-1.1.1g-r0: trying to overwrite etc/ssl/openssl.cnf owned by libressl2.6-libcrypto-2.6.5-r0.
(2/2) Installing ca-certificates (20191127-r1)
Executing busybox-1.27.2-r11.trigger
Executing ca-certificates-20191127-r1.trigger
1 error; 8 MiB in 15 packages
The command '/bin/sh -c echo -e "https://mirrors.ustc.edu.cn/alpine/latest-stable/main\nhttps://mirrors.ustc.edu.cn/alpine/latest-stable/community" > /etc/apk/repositories && apk add --update ca-certificates && update-ca-certificates' returned a non-zero code: 1
`

**Comment by xuhua912** [comment]
`
# docker build -f build/ks-controller-manager/Dockerfile -t harbor.belle.net.cn:8443/ks-controller-manager:2.1.1 .
Sending build context to Docker daemon  141.6MB
Step 1/8 : FROM golang:1.12 as controller-manager-builder
 ---> ffcaee6f7d8b
Step 2/8 : COPY / /go/src/kubesphere.io/kubesphere
 ---> ce4ec5aec998
Step 3/8 : WORKDIR /go/src/kubesphere.io/kubesphere
 ---> Running in 653b62e681e8
Removing intermediate container 653b62e681e8
 ---> fd87a5dbab82
Step 4/8 : RUN CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 GOFLAGS=-mod=vendor go build --ldflags "-extldflags -static" -o controller-manager ./cmd/controller-manager/
 ---> Running in a9dda2856eed
Removing intermediate container a9dda2856eed
 ---> 88b836d3e8e7
Step 5/8 : FROM alpine:3.7
 ---> 6d1ef012b567
Step 6/8 : RUN echo -e "https://mirrors.ustc.edu.cn/alpine/latest-stable/main\nhttps://mirrors.ustc.edu.cn/alpine/latest-stable/community" > /etc/apk/repositories && apk add --update ca-certificates && update-ca-certificates
 ---> Running in 4e038f46cf66
fetch https://mirrors.ustc.edu.cn/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.ustc.edu.cn/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libcrypto1.1 (1.1.1g-r0)
ERROR: libcrypto1.1-1.1.1g-r0: trying to overwrite etc/ssl/openssl.cnf owned by libressl2.6-libcrypto-2.6.5-r0.
(2/2) Installing ca-certificates (20191127-r1)
Executing busybox-1.27.2-r11.trigger
Executing ca-certificates-20191127-r1.trigger
1 error; 8 MiB in 15 packages
The command '/bin/sh -c echo -e "https://mirrors.ustc.edu.cn/alpine/latest-stable/main\nhttps://mirrors.ustc.edu.cn/alpine/latest-stable/community" > /etc/apk/repositories && apk add --update ca-certificates && update-ca-certificates' returned a non-zero code: 1
`

**Comment by LinuxSuRen** [comment]
I'm not sure if you already fixed this problem. But please contact https://github.com/kubesphere/kubesphere/issues if it's not.

/close
