### ISSUE TITLE
Account is always logged out in demo.kubesphere.io 

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/community#93]
Each account has this abnormal phenomenon in demo.kubesphere.io, how to solve it? BTW, the demo environment is v2.1.0.
![image](https://user-images.githubusercontent.com/40452856/84584441-12332f00-ae37-11ea-86a9-c36ed71df39b.png)

**Comment by wansir** [comment]
Multi login is enabled now.

**Comment by FeynmanZhou** [comment]
@wansir  It seems this issue is not caused by others logging in. Every time when I log in, it instantly reminds me someone has logged in this account.
